### ISSUE TITLE
[Bug] 我从控制台看到如下错误

### ISSUE THREAD

**Issue by yjc980121** [apache/iotdb#10113]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

win server 2022
iotdb 1.1.0 
iotdb配置信息基本都未改动，只启用了mqtt，监听 0.0.0.0，更换了服务器名，也应该不影响

### Describe the bug and provide the minimal reproduce step

2023-06-10 23:10:38,700 [pool-23-IoTDB-Compaction-5] INFO  o.a.i.d.e.c.e.e.CompactionExceptionHandler:62 - root.advint-4 [Compaction][ExceptionHandler] inner space compaction start handling exception, source seqFiles is [file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686212425941-1-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686223592074-2-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686228498724-3-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686233423478-4-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686238341041-5-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686243233477-6-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686248151030-7-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686253053790-8-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686257966086-9-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686262891409-10-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686267820436-11-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686272737635-12-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686277657815-13-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686282578163-14-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686287489219-15-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686298203441-16-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686304551328-17-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686310901318-18-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686317247962-19-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686323602554-20-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686329952871-21-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686336298831-22-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686342651655-23-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686349006564-24-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686355381018-25-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686361762506-26-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686368110409-27-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686374474935-28-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686380808356-29-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686387162470-30-0-0.tsfile, status: COMPACTING], source unseqFiles is [].
2023-06-10 23:10:38,703 [pool-23-IoTDB-Compaction-1] ERROR o.a.i.d.e.c.e.t.InnerSpaceCompactionTask:269 - root.advint-2 [Compaction] Meet errors in inner space compaction.
java.io.IOException: Uncompress error! uncompress size: 18compressed size: 2761page header: PageHeader{uncompressedSize=18, compressedSize=2761, statistics=startTime: 1686293517940 endTime: 1686297410701 count: 1781 [minValue:0.0,maxValue:0.0,firstValue:0.0,lastValue:0.0,sumValue:0.0]}FAILED_TO_UNCOMPRESS(5)
        at org.apache.iotdb.tsfile.read.reader.chunk.ChunkReader.constructPageReaderForNextPage(ChunkReader.java:201)
        at org.apache.iotdb.tsfile.read.reader.chunk.ChunkReader.initAllPageReaders(ChunkReader.java:124)
        at org.apache.iotdb.tsfile.read.reader.chunk.ChunkReader.<init>(ChunkReader.java:81)
        at org.apache.iotdb.db.engine.compaction.execute.utils.executor.readchunk.SingleSeriesCompactionExecutor.writeChunkIntoChunkWriter(SingleSeriesCompactionExecutor.java:251)
        at org.apache.iotdb.db.engine.compaction.execute.utils.executor.readchunk.SingleSeriesCompactionExecutor.writeCachedChunkIntoChunkWriter(SingleSeriesCompactionExecutor.java:277)
        at org.apache.iotdb.db.engine.compaction.execute.utils.executor.readchunk.SingleSeriesCompactionExecutor.processSmallChunk(SingleSeriesCompactionExecutor.java:242)
        at org.apache.iotdb.db.engine.compaction.execute.utils.executor.readchunk.SingleSeriesCompactionExecutor.execute(SingleSeriesCompactionExecutor.java:148)
        at org.apache.iotdb.db.engine.compaction.execute.performer.impl.ReadChunkCompactionPerformer.compactNotAlignedSeries(ReadChunkCompactionPerformer.java:183)
        at org.apache.iotdb.db.engine.compaction.execute.performer.impl.ReadChunkCompactionPerformer.perform(ReadChunkCompactionPerformer.java:87)
        at org.apache.iotdb.db.engine.compaction.execute.task.InnerSpaceCompactionTask.doCompaction(InnerSpaceCompactionTask.java:150)
        at org.apache.iotdb.db.engine.compaction.execute.task.AbstractCompactionTask.start(AbstractCompactionTask.java:80)
        at org.apache.iotdb.db.engine.compaction.schedule.CompactionWorker.run(CompactionWorker.java:65)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2023-06-10 23:11:38,696 [pool-23-IoTDB-Compaction-3] INFO  o.a.i.d.e.c.e.t.InnerSpaceCompactionTask:113 - root.advint-4 [Compaction] Sequence InnerSpaceCompaction task starts with 30 files, total file size is 1 MB.
2023-06-10 23:11:38,699 [pool-23-IoTDB-Compaction-3] INFO  o.a.i.d.e.c.e.t.InnerSpaceCompactionTask:137 - root.advint-4 [Compaction] compaction with [file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686212425941-1-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686223592074-2-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686228498724-3-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686233423478-4-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686238341041-5-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686243233477-6-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686248151030-7-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686253053790-8-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686257966086-9-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686262891409-10-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686267820436-11-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686272737635-12-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686277657815-13-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686282578163-14-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686287489219-15-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686298203441-16-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686304551328-17-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686310901318-18-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686317247962-19-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686323602554-20-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686329952871-21-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686336298831-22-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686342651655-23-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686349006564-24-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686355381018-25-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686361762506-26-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686368110409-27-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686374474935-28-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686380808356-29-0-0.tsfile, status: COMPACTING, file is E:\databases_tools\IotDB\1.1.0\apache-iotdb-1.1.0-all-bin\data\datanode\data\sequence\root.advint\4\2788\1686387162470-30-0-0.tsfile, status: COMPACTING]
2023-06-10 23:11:38,705 [pool-23-IoTDB-Compaction-3] ERROR o.a.i.d.e.c.e.t.InnerSpaceCompactionTask:269 - root.advint-4 [Compaction] Meet errors in inner space compaction.
org.apache.iotdb.commons.exception.IllegalPathException: root.advint.aaa.鐠佹儳鐣惧〒鈺佸 is not a legal path
        at org.apache.iotdb.commons.utils.PathUtils.splitPathToDetachedNodes(PathUtils.java:48)
        at org.apache.iotdb.commons.path.PartialPath.<init>(PartialPath.java:82)
        at org.apache.iotdb.db.engine.compaction.execute.performer.impl.ReadChunkCompactionPerformer.compactNotAlignedSeries(ReadChunkCompactionPerformer.java:174)
        at org.apache.iotdb.db.engine.compaction.execute.performer.impl.ReadChunkCompactionPerformer.perform(ReadChunkCompactionPerformer.java:87)
        at org.apache.iotdb.db.engine.compaction.execute.task.InnerSpaceCompactionTask.doCompaction(InnerSpaceCompactionTask.java:150)
        at org.apache.iotdb.db.engine.compaction.execute.task.AbstractCompactionTask.start(AbstractCompactionTask.java:80)
        at org.apache.iotdb.db.engine.compaction.schedule.CompactionWorker.run(CompactionWorker.java:65)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

经过查找原因，我发现我采集过快(发送MQTT消息采集)，不知道采集过快为什么会报错，另外，上述另外一个错误说路径非法，经过查看，是乱码部分，但是实际上是因为我采集物理量使用了中文，iotdb也是支持的,并不是路径部分。
此外，我的采集程序从6月8日开始采集，但是我今日查看，只找到少部分，6月8日和6月9日数据，不知道怎么发生采集数据丢失情况。

### What did you expect to see?

解决或者解释数据丢失情况，以避免后续继续发生此情况。
![1686410373073](https://github.com/apache/iotdb/assets/3898524/931b2e00-24b7-4615-bc72-c833f8d1f789)
[iotdb_logs.zip](https://github.com/apache/iotdb/files/11712727/iotdb_logs.zip)

### What did you see instead?

fix bug

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by choubenson** [comment]
Thank you very much for submitting questions about iotdb, we welcome any questions from users. In order to further analyze the problem, we need some data files, please add my WeChat (benson19971204), we can solve the problem faster :)

**Comment by yjc980121** [comment]
最近的1.2.1已修复问题
