### ISSUE TITLE
UnsupportedOperationException when try to restart dataNode

### ISSUE THREAD

**Issue by LangYuanzh** [apache/iotdb#10362]
version: 1.1.0
I deployment iotdb basedon  HDFS as data storage.
config:
schema_replication_factor=1
data_replication_factor=2

when one dataNode is failed and try to restart it, there is such exception:
ERROR o.a.i.c.c.t.WrappedThreadPoolExecutor:108 - Exception in thread pool org.apache.iotdb.threadpool:type=StorageEngine
java.lang.UnsupportedOperationException: Unsupported operation.
        at org.apache.iotdb.hadoop.fileSystem.HDFSFile.getCanonicalPath(HDFSFile.java:308)
        at org.apache.iotdb.db.wal.recover.WALRecoverManager.addRecoverPerformer(WALRecoverManager.java:181)
        at org.apache.iotdb.db.engine.storagegroup.DataRegion.recoverUnsealedTsFile(DataRegion.java:774)
        at org.apache.iotdb.db.engine.storagegroup.DataRegion.recover(DataRegion.java:483)
        at org.apache.iotdb.db.engine.storagegroup.DataRegion.<init>(DataRegion.java:345)
        at org.apache.iotdb.db.engine.StorageEngine.buildNewDataRegion(StorageEngine.java:459)
        at org.apache.iotdb.db.engine.StorageEngine.lambda$asyncRecover$2(StorageEngine.java:255)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by HTHou** [comment]
Since IoTDB supported cluster mode for HA, HDFS is not fully supported. That is the reason why the configuration is hidden. We don't recommend to use it in current version.

**Comment by LangYuanzh** [comment]
> Since IoTDB supported cluster mode for HA, HDFS is not fully supported. That is the reason why the configuration is hidden. We don't recommend to use it in current version.

It's there any plan to fully support HDFS?
