### ISSUE TITLE
iotdb在python无法运行

### ISSUE THREAD

**Issue by golden-memory** [apache/iotdb#11048]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

python=3.11.5，apache-iotdb=1.1.2，thrift=0.16.0环境中，iotdb用不了，无法运行，连都连不了

### Describe the bug and provide the minimal reproduce step

session closed because: 
Traceback (most recent call last):
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\iotdb\Session.py", line 130, in open
    open_resp = self.__client.openSession(open_req)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\iotdb\thrift\rpc\IClientRPCService.py", line 722, in openSession
    return self.recv_openSession()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\iotdb\thrift\rpc\IClientRPCService.py", line 739, in recv_openSession
    raise x
thrift.Thrift.TApplicationException: Internal error processing openSession
Traceback (most recent call last):
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\iotdb\Session.py", line 1027, in set_time_zone
    status = self.__client.setTimeZone(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\iotdb\thrift\rpc\IClientRPCService.py", line 1073, in setTimeZone
    self.send_setTimeZone(req)
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\iotdb\thrift\rpc\IClientRPCService.py", line 1082, in send_setTimeZone
    self._oprot.trans.flush()
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\thrift\transport\TTransport.py", line 304, in flush
    self.__trans.write(buf)
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\thrift\transport\TSocket.py", line 172, in write
    raise TTransportException(type=TTransportException.NOT_OPEN,
thrift.transport.TTransport.TTransportException: Transport not open

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\my_projects\kmsnPython\code\myTest.py", line 14, in <module>
    session.open(False)
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\iotdb\Session.py", line 150, in open
    self.set_time_zone(self.__zone_id)
  File "D:\my_softs\anaconda\envs\kmsnMy\Lib\site-packages\iotdb\Session.py", line 1034, in set_time_zone
    raise RuntimeError("Could not set time zone because: ", e)
RuntimeError: ('Could not set time zone because: ', TTransportException('Transport not open'))

Process finished with exit code 1

### What did you expect to see?

1

### What did you see instead?

1

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by HTHou** [comment]
apache-iotdb=1.1.2 只是客户端，iotdb的服务端启动了吗？
