### ISSUE TITLE
how to make standalone version managed by systemd in centos7,i have tried,but always failed

### ISSUE THREAD

**Issue by wxcoin** [apache/iotdb#11563]
[root@k8s-node1 iotdb]# cat /usr/lib/systemd/system/iotdb.service
[Unit]
Description=iotdb service
After=syslog.target

[Service]
Type = simple
Environment="IOTDB_HOME=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin"
User=root
Group=root
ExecStart = /home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/start-standalone.sh
ExecStop = /home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/stop-standalone.sh
Restart=on-failure

[Install]
WantedBy=multi-user.target

[root@k8s-node1 iotdb]# systemctl start iotdb
[root@k8s-node1 iotdb]# systemctl status iotdb
● iotdb.service - iotdb service
Loaded: loaded (/usr/lib/systemd/system/iotdb.service; disabled; vendor preset: disabled)
Active: deactivating (stop-sigterm) (Result: exit-code) since Thu 2023-11-16 19:53:20 CST; 1s ago
Process: 28329 ExecStop=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/stop-standalone.sh (code=exited, status=1/FAILURE)
Process: 27587 ExecStart=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/start-standalone.sh (code=exited, status=0/SUCCESS)
Main PID: 27587 (code=exited, status=0/SUCCESS)
Tasks: 72
Memory: 655.5M
CGroup: /system.slice/iotdb.service
└─27588 java -Dlogback.configurationFile=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/../conf/logback-confignode.xml -DCONFIGNODE_HOME=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-...

Nov 16 19:53:17 k8s-node1 systemd[1]: Started iotdb service.
Nov 16 19:53:20 k8s-node1 start-standalone.sh[27587]: Execute start-standalone.sh finished, you can see more details in the logs of confignode and datanode
Nov 16 19:53:20 k8s-node1 stop-standalone.sh[28329]: Check whether the internal_port is used..., port is 10710
Nov 16 19:53:20 k8s-node1 stop-standalone.sh[28329]: Stop ConfigNode, PID: 27588
Nov 16 19:53:20 k8s-node1 stop-standalone.sh[28329]: Check whether the rpc_port is used..., port is 6667
Nov 16 19:53:20 k8s-node1 stop-standalone.sh[28329]: No DataNode to stop
Nov 16 19:53:20 k8s-node1 systemd[1]: iotdb.service: control process exited, code=exited status=1
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]# systemctl status iotdb
● iotdb.service - iotdb service
Loaded: loaded (/usr/lib/systemd/system/iotdb.service; disabled; vendor preset: disabled)
Active: active (running) since Thu 2023-11-16 19:53:57 CST; 2s ago
Process: 782 ExecStop=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/stop-standalone.sh (code=exited, status=1/FAILURE)
Main PID: 1234 (start-standalon)
Tasks: 94
Memory: 553.4M
CGroup: /system.slice/iotdb.service
├─1234 /bin/bash /home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/start-standalone.sh
├─1235 java -Dlogback.configurationFile=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/../conf/logback-confignode.xml -DCONFIGNODE_HOME=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-a...
└─1236 sleep 3

Nov 16 19:53:57 k8s-node1 systemd[1]: Started iotdb service.
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]# systemctl status iotdb
● iotdb.service - iotdb service
Loaded: loaded (/usr/lib/systemd/system/iotdb.service; disabled; vendor preset: disabled)
Active: active (running) since Thu 2023-11-16 19:54:20 CST; 233ms ago
Process: 3417 ExecStop=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/stop-standalone.sh (code=exited, status=1/FAILURE)
Main PID: 4122 (start-standalon)
Tasks: 6
Memory: 4.6M
CGroup: /system.slice/iotdb.service
├─4122 /bin/bash /home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/start-standalone.sh
├─4123 bash /home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/start-confignode.sh
├─4124 sleep 3
└─4148 bash /home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/start-confignode.sh

Nov 16 19:54:20 k8s-node1 systemd[1]: Started iotdb service.
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]#
[root@k8s-node1 iotdb]# systemctl status iotdb
● iotdb.service - iotdb service
Loaded: loaded (/usr/lib/systemd/system/iotdb.service; disabled; vendor preset: disabled)
Active: deactivating (stop-sigterm) (Result: exit-code) since Thu 2023-11-16 19:54:23 CST; 1s ago
Process: 4716 ExecStop=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/stop-standalone.sh (code=exited, status=1/FAILURE)
Process: 4122 ExecStart=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/start-standalone.sh (code=exited, status=0/SUCCESS)
Main PID: 4122 (code=exited, status=0/SUCCESS)
Tasks: 72
Memory: 660.4M
CGroup: /system.slice/iotdb.service
└─4123 java -Dlogback.configurationFile=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/../conf/logback-confignode.xml -DCONFIGNODE_HOME=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-a...

Nov 16 19:54:20 k8s-node1 systemd[1]: Started iotdb service.
Nov 16 19:54:23 k8s-node1 start-standalone.sh[4122]: Execute start-standalone.sh finished, you can see more details in the logs of confignode and datanode
Nov 16 19:54:23 k8s-node1 stop-standalone.sh[4716]: Check whether the internal_port is used..., port is 10710
Nov 16 19:54:23 k8s-node1 stop-standalone.sh[4716]: Stop ConfigNode, PID: 4123
Nov 16 19:54:23 k8s-node1 stop-standalone.sh[4716]: Check whether the rpc_port is used..., port is 6667
Nov 16 19:54:24 k8s-node1 stop-standalone.sh[4716]: No DataNode to stop
Nov 16 19:54:24 k8s-node1 systemd[1]: iotdb.service: control process exited, code=exited status=1
[root@k8s-node1 iotdb]# systemctl status iotdb
● iotdb.service - iotdb service
Loaded: loaded (/usr/lib/systemd/system/iotdb.service; disabled; vendor preset: disabled)
Active: deactivating (stop-sigterm) (Result: exit-code) since Thu 2023-11-16 20:00:22 CST; 597ms ago
Process: 21778 ExecStop=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/stop-standalone.sh (code=exited, status=1/FAILURE)
Process: 21033 ExecStart=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/start-standalone.sh (code=exited, status=0/SUCCESS)
Main PID: 21033 (code=exited, status=0/SUCCESS)
Tasks: 93
Memory: 675.2M
CGroup: /system.slice/iotdb.service
└─21034 java -Dlogback.configurationFile=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-all-bin/sbin/../conf/logback-confignode.xml -DCONFIGNODE_HOME=/home/infrastracture/apache-[iotdb-1](https://issues.apache.org/jira/browse/IOTDB-1).2.2-...

Nov 16 20:00:19 k8s-node1 systemd[1]: Started iotdb service.
Nov 16 20:00:22 k8s-node1 start-standalone.sh[21033]: Execute start-standalone.sh finished, you can see more details in the logs of confignode and datanode
Nov 16 20:00:22 k8s-node1 stop-standalone.sh[21778]: Check whether the internal_port is used..., port is 10710
Nov 16 20:00:22 k8s-node1 stop-standalone.sh[21778]: Stop ConfigNode, PID: 21034
Nov 16 20:00:22 k8s-node1 stop-standalone.sh[21778]: Check whether the rpc_port is used..., port is 6667
Nov 16 20:00:22 k8s-node1 stop-standalone.sh[21778]: No DataNode to stop
Nov 16 20:00:22 k8s-node1 systemd[1]: iotdb.service: control process exited, code=exited status=1

Nov 16 20:00:07 k8s-node1 start-standalone.sh: Execute start-standalone.sh finished, you can see more details in the logs of confignode and datanode
Nov 16 20:00:07 k8s-node1 stop-standalone.sh: Check whether the internal_port is used..., port is 10710
Nov 16 20:00:07 k8s-node1 stop-standalone.sh: Stop ConfigNode, PID: 19158
Nov 16 20:00:07 k8s-node1 stop-standalone.sh: Check whether the rpc_port is used..., port is 6667
Nov 16 20:00:07 k8s-node1 stop-standalone.sh: No DataNode to stop
Nov 16 20:00:07 k8s-node1 systemd: iotdb.service: control process exited, code=exited status=1

**Comment by wxcoin** [comment]
2023-11-17 10:23:09,950 [main] INFO  o.a.i.c.c.ConfigNodeDescriptor:105 - Start to read config file file:/home/infrastracture/apache-iotdb-1.2.2-all-bin/sbin/../conf/iotdb-common.properties 
2023-11-17 10:23:09,957 [main] INFO  o.a.i.c.c.ConfigNodeDescriptor:124 - start reading ConfigNode conf file: file:/home/infrastracture/apache-iotdb-1.2.2-all-bin/sbin/../conf/iotdb-confignode.properties 
2023-11-17 10:23:09,970 [main] INFO  o.a.i.c.s.ConfigNode:99 - IoTDB-ConfigNode environment variables: 
	CONFIGNODE_HOME=/home/infrastracture/apache-iotdb-1.2.2-all-bin/sbin/..;
	CONFIGNODE_CONF=/home/infrastracture/apache-iotdb-1.2.2-all-bin/sbin/../conf; 
2023-11-17 10:23:09,970 [main] INFO  o.a.i.c.s.ConfigNode:103 - IoTDB-ConfigNode default charset is: UTF-8 
2023-11-17 10:23:09,971 [main] INFO  o.a.i.c.s.ConfigNodeCommandLine:68 - Running mode -s 
2023-11-17 10:23:09,971 [main] INFO  o.a.i.c.s.ConfigNodeCommandLine:72 - Starting IoTDB 1.2.2 (Build: 5d0bfb0) 
2023-11-17 10:23:09,974 [main] INFO  o.a.i.c.c.ConfigNodeStartupCheck:65 - configNode port check successful. 
2023-11-17 10:23:09,974 [main] INFO  o.a.i.c.s.StartupChecks:59 - Start JMX locally. 
2023-11-17 10:23:09,975 [main] INFO  o.a.i.c.s.StartupChecks:45 - JDK version is 8. 
2023-11-17 10:23:09,977 [main] INFO  o.a.i.c.s.ConfigNode:111 - Activating IoTDB-ConfigNode... 
2023-11-17 10:23:09,979 [main] INFO  o.a.i.c.s.ConfigNode:249 - Successfully setup internal services. 
2023-11-17 10:23:10,004 [main] INFO  o.a.i.c.a.a.BasicAuthorizer$InstanceHolder:98 - Authorizer provider class: org.apache.iotdb.commons.auth.authorizer.LocalFileAuthorizer 
2023-11-17 10:23:10,013 [main] WARN  o.a.i.c.a.u.BasicUserManager:78 - Cannot load admin, Creating a new one 
org.apache.iotdb.commons.auth.AuthException: java.io.IOException: java.io.EOFException
	at org.apache.iotdb.commons.auth.user.BasicUserManager.getUser(BasicUserManager.java:103)
	at org.apache.iotdb.commons.auth.user.BasicUserManager.initAdmin(BasicUserManager.java:76)
	at org.apache.iotdb.commons.auth.user.BasicUserManager.reset(BasicUserManager.java:295)
	at org.apache.iotdb.commons.auth.user.BasicUserManager.<init>(BasicUserManager.java:65)
	at org.apache.iotdb.commons.auth.user.LocalFileUserManager.<init>(LocalFileUserManager.java:31)
	at org.apache.iotdb.commons.auth.authorizer.LocalFileAuthorizer.<init>(LocalFileAuthorizer.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.iotdb.commons.auth.authorizer.BasicAuthorizer$InstanceHolder.<clinit>(BasicAuthorizer.java:101)
	at org.apache.iotdb.commons.auth.authorizer.BasicAuthorizer.getInstance(BasicAuthorizer.java:83)
	at org.apache.iotdb.confignode.persistence.AuthorInfo.<init>(AuthorInfo.java:71)
	at org.apache.iotdb.confignode.manager.ConfigManager.<init>(ConfigManager.java:259)
	at org.apache.iotdb.confignode.service.ConfigNode.initConfigManager(ConfigNode.java:293)
	at org.apache.iotdb.confignode.service.ConfigNode.active(ConfigNode.java:120)
	at org.apache.iotdb.confignode.service.ConfigNodeCommandLine.run(ConfigNodeCommandLine.java:79)
	at org.apache.iotdb.commons.ServerCommandLine.doMain(ServerCommandLine.java:58)
	at org.apache.iotdb.confignode.service.ConfigNode.main(ConfigNode.java:107)
Caused by: java.io.IOException: java.io.EOFException
	at org.apache.iotdb.commons.auth.user.LocalFileUserAccessor.loadUser(LocalFileUserAccessor.java:138)
	at org.apache.iotdb.commons.auth.user.BasicUserManager.getUser(BasicUserManager.java:97)
	... 18 common frames omitted
Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.iotdb.commons.utils.IOUtils.readString(IOUtils.java:102)
	at org.apache.iotdb.commons.auth.user.LocalFileUserAccessor.loadUser(LocalFileUserAccessor.java:108)
	... 19 common frames omitted

**Comment by HTHou** [comment]
See #11629
