### ISSUE TITLE
IoTDB的监控网页异常

### ISSUE THREAD

**Issue by FoxNo2** [apache/iotdb#1187]
使用IoTDB的 0.10.0-SNAPSHOT版本.
IoTDB无数据时,访问IP:8181可以正常显示监控网页,当写入数据后,再次访问,网页报出500异常.
java.lang.NullPointerException
	at org.apache.iotdb.db.metrics.ui.MetricsPage.sqlRow(MetricsPage.java:120)
	at org.apache.iotdb.db.metrics.ui.MetricsPage.render(MetricsPage.java:83)
	at org.apache.iotdb.db.metrics.server.QueryServlet.doGet(QueryServlet.java:42)
查看MetricsPage.java的第120行:
```java
+ "<td>" + (errMsg.equals("") ? "== Parsed Physical Plan ==" : errMsg)
```
是否为此处errMsg为NULL导致,为何写入数据后会报出异常?

**Comment by jixuan1989** [comment]
多谢！ @Genius-pig 可以看一下吗

**Comment by Genius-pig** [comment]
这个bug确实存在，metrics界面也有其他问题。我正在开发新的界面，你可以等到新的监控界面出来吗？ @FoxNo2

**Comment by FoxNo2** [comment]
@Genius-pig 当然,多谢!.

**Comment by kqkdChen** [comment]
希望新的界面可以加快进度，然后把界面原本没有实现的功能excute sql也给实现了
