### ISSUE TITLE
突然停电后，iotdb重启失败

### ISSUE THREAD

**Issue by ClancyLv** [apache/iotdb#12453]
使用iotdb版本号：1.2.2 服务器版本：Linux lyc-uos 4.19.0-91.82.152.uelc20.x86_64 #1 SMP Fri May 12 22:38:01 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
突然停电后来电，其他mysql、redis正常开机启动，iotdb无法正常开机启动，iotdb已配置开机自启，后来手动执行启动脚本start-standalone.sh还是失败，部分日志如下：2024-04-30 13:06:11,854 [pool-37-IoTDB-ClientRPC-Processor-1] ERROR o.a.i.d.a.ClusterAuthorityFetcher:210 - Failed to connect to config node. 
2024-04-30 13:06:13,165 [IoTDB-Shutdown-Hook] ERROR o.a.i.d.s.IoTDBShutdownHook:124 - Failed to report shutdown 
org.apache.thrift.TException: Error in calling method reportDataNodeShutdown, because: Fail to connect to any config node. Please check status of ConfigNodes or logs of connected DataNode
	at org.apache.iotdb.commons.client.sync.SyncThriftClientWithErrorHandler.intercept(SyncThriftClientWithErrorHandler.java:57)
	at org.apache.iotdb.db.protocol.client.ConfigNodeClient$$EnhancerByCGLIB$$713d1e1e.reportDataNodeShutdown(<generated>)
	at org.apache.iotdb.db.service.IoTDBShutdownHook.run(IoTDBShutdownHook.java:119)
Caused by: org.apache.thrift.TException: Fail to connect to any config node. Please check status of ConfigNodes or logs of connected DataNode
	at org.apache.iotdb.db.protocol.client.ConfigNodeClient.tryToConnect(ConfigNodeClient.java:268)
	at org.apache.iotdb.db.protocol.client.ConfigNodeClient.waitAndReconnect(ConfigNodeClient.java:237)
	at org.apache.iotdb.db.protocol.client.ConfigNodeClient.executeRemoteCallWithRetry(ConfigNodeClient.java:345)
	at org.apache.iotdb.db.protocol.client.ConfigNodeClient.reportDataNodeShutdown(ConfigNodeClient.java:406)
	at org.apache.iotdb.db.protocol.client.ConfigNodeClient$$EnhancerByCGLIB$$713d1e1e.CGLIB$reportDataNodeShutdown$6(<generated>)
	at org.apache.iotdb.db.protocol.client.ConfigNodeClient$$EnhancerByCGLIB$$713d1e1e$$FastClassByCGLIB$$600dc9c5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.apache.iotdb.commons.client.sync.SyncThriftClientWithErrorHandler.intercept(SyncThriftClientWithErrorHandler.java:53)
	... 2 common frames omitted
2024-04-30 13:06:13,165 [IoTDB-Shutdown-Hook] ERROR o.a.i.d.s.IoTDBShutdownHook:127 - Reporting DataNode shutdown failed. The cluster will still take the current DataNode as Running for a few seconds. 
[iotdb-log.zip](https://github.com/apache/iotdb/files/15158550/iotdb-log.zip)

**Comment by CritasWang** [comment]
日志信息中 confignode 在13:06:07 时 启动后，13:06:11 停止掉了。所以 datanode 无法连接到 confignode 因此启动失败
