### ISSUE TITLE
[Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB

### ISSUE THREAD

**Issue by hupengwu** [apache/iotdb#12498]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.3.1

### Describe the bug and provide the minimal reproduce step

当我使用iotdb-session的Session范例的代码，连接上IoTDB之后，
使用IoTDB的stop-all.sh，start-all.sh的命令进行重启IoTDB，
那么，Session范例的代码，将永远无法连接上远程的IoTDB。

相关异常信息
Exception in thread "main" org.apache.iotdb.rpc.IoTDBConnectionException: Fail to reconnect to server. Please check server status.192.168.1.23:6667
	at org.apache.iotdb.session.SessionConnection.<init>(SessionConnection.java:132)
	at org.apache.iotdb.session.Session.constructSessionConnection(Session.java:592)
	at org.apache.iotdb.session.Session.open(Session.java:501)
	at org.apache.iotdb.session.Session.open(Session.java:459)

一直到我使用start-cli.sh命令，连接过一次IoTDB后，Session范例的代码才能重新连接上IoTDB

### What did you expect to see?

当IoTDB重启后，使用iotdb-session的JAVA客户端应用，能够重新连接上IoTDB

### What did you see instead?

当IoTDB重启后，使用iotdb-session的JAVA客户端应用，就无法连接上IoTDB

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by CritasWang** [comment]
使用IoTDB的stop-all.sh，start-all.sh的命令进行重启IoTDB，
那么，Session范例的代码，将永远无法连接上远程的IoTDB。

重启之后看下对应的 log_confignode_all.log 和 log_datanode.all.log

**Comment by hupengwu** [comment]
清理日志文件，重新复现问题后，


在这两个日志文件中，没有看到异常和出错信息


附件中，是日志文件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/iotdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)





 
使用IoTDB的stop-all.sh，start-all.sh的命令进行重启IoTDB，
 那么，Session范例的代码，将永远无法连接上远程的IoTDB。
 
重启之后看下对应的 log_confignode_all.log 和 log_datanode.all.log

**Comment by CritasWang** [comment]
直接 运行  ./sbin/start-confignode.sh 看下

**Comment by hupengwu** [comment]
这是问题出现，到启动start-cli.sh后，客户端java代码重新连接正常的日志


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "江南"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 中午12:24
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)



清理日志文件，重新复现问题后，


在这两个日志文件中，没有看到异常和出错信息


附件中，是日志文件


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "apache/iotdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)





 
使用IoTDB的stop-all.sh，start-all.sh的命令进行重启IoTDB，
 那么，Session范例的代码，将永远无法连接上远程的IoTDB。
 
重启之后看下对应的 log_confignode_all.log 和 log_datanode.all.log

**Comment by CritasWang** [comment]
启动不是立刻成功的，可以观察 datanode 的日志启动成功后再使用 session 去连接

**Comment by hupengwu** [comment]
运行./sbin/start-confignode.sh后，故障现象依然存在


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/iotdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 中午12:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)





 
直接 运行  ./sbin/start-confignode.sh 看下

**Comment by hupengwu** [comment]
真正能够连接上去，必须要运行过一次start-cli.sh后，才能连接成功





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 中午12:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)




 
直接 运行  ./sbin/start-confignode.sh 看下

**Comment by hupengwu** [comment]
这个前面怀疑过，实际上等待比较长的时间后，依然连接不上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/iotdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 中午12:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)





 
启动不是立刻成功的，可以观察 datanode 的日志启动成功后再使用 session 去连接

**Comment by CritasWang** [comment]
这个现象从来没见过。
启动后，session 连接不上时 不先用 start-cli.sh 先看看日志，看看 6667 的端口占用情况。

**Comment by hupengwu** [comment]
我的运行环境
UBUNTU20.0
openjdk 11
友善的r5c设备 CPU是RK3568的ARM嵌入式设备



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 中午12:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)




 
这个现象从来没见过。
 启动后，session 连接不上时 不先用 start-cli.sh 先看看日志，看看 6667 的端口占用情况。

**Comment by hupengwu** [comment]
我下午复现问题后，再看一下端口占用状况





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 中午12:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)




 
这个现象从来没见过。
 启动后，session 连接不上时 不先用 start-cli.sh 先看看日志，看看 6667 的端口占用情况。

**Comment by hupengwu** [comment]
我这个设备环境，同时具备IPV6和IPV4


比如，nginx，同时占用ipv6和ipv4的80端口


但是，iotdb，只绑定了ipv6的6667端口，并不是ipv4











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/iotdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 中午12:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/iotdb] [Bug] 当IoTDB重启的时候，Session范例的连接IoTDB的代码，将无法再远程连接上IoTDB (Issue #12498)





 
这个现象从来没见过。
 启动后，session 连接不上时 不先用 start-cli.sh 先看看日志，看看 6667 的端口占用情况。

**Comment by CritasWang** [comment]
@hupengwu 这个有新的进展吗
