### ISSUE TITLE
昨天运行了半天，早上出现的问题ERROR o.a.t.s.TThreadPoolServer$WorkerProcess:258 

### ISSUE THREAD

**Issue by zhqingyong** [apache/iotdb#12492]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

用的windows版的一键部署包，最新的1.3.1，原来是下载的1.3.0完整包，通过替换lib文件夹升级的1.3.1最新

### Describe the bug and provide the minimal reproduce step

2024-05-09 08:07:06,644 [pool-4-thread-1$20240509_000706_56966_1.1.0] INFO  o.a.i.c.i.IoTConsensusServerImpl:210 - DataRegion[DataRegion[7]]: index after build: safeIndex:8799999, searchIndex: 8800000 
2024-05-09 08:10:41,595 [pool-21-IoTDB-Timed-Flush-Seq-Memtable-1] INFO  o.a.i.d.s.d.DataRegion:1672 - Exceed sequence memtable flush interval, so flush working memtable of time partition 2835 in database root.4duxin[7] 
2024-05-09 08:10:42,796 [pool-41-IoTDB-ClientRPC-Processor-531] INFO  o.a.i.d.p.s.SessionManager:125 - IoTDB: Login status: Login successfully. User : root, opens Session-3259-root:127.0.0.1:54817 
2024-05-09 08:10:55,874 [pool-41-IoTDB-ClientRPC-Processor-514] ERROR o.a.t.s.TThreadPoolServer$WorkerProcess:258 - Thrift Error occurred during processing of message. 
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
这是什么报错？？
报了后CLI数据库命令行打不开它如下图，workbench也连不上。
数据库的mqtt服务正常接收数据但不写入了，REST api能连上并可以查询到8：07分报错前的数据。

### What did you expect to see?

如何解决？怎么造成的

### What did you see instead?

![591a9ef4a60635cc35cf8037ee30446](https://github.com/apache/iotdb/assets/29061583/6801f1f6-b4fe-40b7-9a93-1f6cb55f440c)
cli卡在这

### Anything else?

123

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhqingyong** [comment]
2024-05-09 08:07:06,644 [pool-4-thread-1$20240509_000706_56966_1.1.0] INFO  o.a.i.c.i.IoTConsensusServerImpl:210 - DataRegion[DataRegion[7]]: index after build: safeIndex:8799999, searchIndex: 8800000 
2024-05-09 08:10:41,595 [pool-21-IoTDB-Timed-Flush-Seq-Memtable-1] INFO  o.a.i.d.s.d.DataRegion:1672 - Exceed sequence memtable flush interval, so flush working memtable of time partition 2835 in database root.4duxin[7] 
2024-05-09 08:10:42,796 [pool-41-IoTDB-ClientRPC-Processor-531] INFO  o.a.i.d.p.s.SessionManager:125 - IoTDB: Login status: Login successfully. User : root, opens Session-3259-root:127.0.0.1:54817 
2024-05-09 08:10:55,874 [pool-41-IoTDB-ClientRPC-Processor-514] ERROR o.a.t.s.TThreadPoolServer$WorkerProcess:258 - Thrift Error occurred during processing of message. 
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:178)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
	at org.apache.iotdb.rpc.TElasticFramedTransport.readFrame(TElasticFramedTransport.java:113)
	at org.apache.iotdb.rpc.TElasticFramedTransport.read(TElasticFramedTransport.java:108)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:463)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:361)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:244)
	at org.apache.iotdb.db.protocol.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:50)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176)
	... 12 common frames omitted

**Comment by HTHou** [comment]
鼠标点击过cmd窗口，使程序暂停了？

**Comment by zhqingyong** [comment]
> 鼠标点击过cmd窗口，使程序暂停了？

有可能，复现了下。windows下的  连接重置 暂时未知
