### ISSUE TITLE
[Bug] A large number of error logs are output every minute.

### ISSUE THREAD

**Issue by cy-chengyan** [apache/iotdb#12844]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

docker image: docker.io/apache/iotdb:1.3.2-standalone

### Describe the bug and provide the minimal reproduce step

log files:
1. log_datanode_error.log
2. log_datanode_all.log

A large number of error logs are output every minute as following:

2024-07-03 05:36:45,608 [pool-10-IoTDB-Compaction-Schedule-4] ERROR o.a.i.d.s.d.DataRegion:2434 - Meet error in compaction schedule.
java.lang.NoClassDefFoundError: Could not initialize class org.apache.iotdb.db.storageengine.dataregion.flush.CompressionRatio$CompressionRatioHolder
        at org.apache.iotdb.db.storageengine.dataregion.flush.CompressionRatio.getInstance(CompressionRatio.java:202)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.selector.estimator.AbstractCompactionEstimator.<init>(AbstractCompactionEstimator.java:62)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.selector.estimator.AbstractCrossSpaceEstimator.<init>(AbstractCrossSpaceEstimator.java:35)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.selector.estimator.FastCrossSpaceCompactionEstimator.<init>(FastCrossSpaceCompactionEstimator.java:27)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.selector.ICompactionSelector.getCompactionEstimator(ICompactionSelector.java:70)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.selector.impl.RewriteCrossSpaceCompactionSelector.<init>(RewriteCrossSpaceCompactionSelector.java:92)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.selector.constant.CrossCompactionSelector.createInstance(CrossCompactionSelector.java:46)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.schedule.CompactionScheduler.tryToSubmitCrossSpaceCompactionTask(CompactionScheduler.java:258)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.schedule.CompactionScheduler.scheduleCompaction(CompactionScheduler.java:103)
        at org.apache.iotdb.db.storageengine.dataregion.DataRegion.executeCompaction(DataRegion.java:2430)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.schedule.CompactionScheduleTaskWorker.call(CompactionScheduleTaskWorker.java:69)
        at org.apache.iotdb.db.storageengine.dataregion.compaction.schedule.CompactionScheduleTaskWorker.call(CompactionScheduleTaskWorker.java:34)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

### What did you expect to see?

The file can be compressed normally and no error log should be output.

### What did you see instead?

None

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by shuwenwei** [comment]
You can check if there is a file with negative number under data/datanode/system/compression_ratio/

**Comment by HTHou** [comment]
Hi, which type timeseries are you using? Aligned timeseries or non aligned timeseries?

**Comment by cy-chengyan** [comment]
> Hi, which type timeseries are you using? Aligned timeseries or non aligned timeseries?

Aligned timeseries.

**Comment by shuwenwei** [comment]
Hi, can you upload recent log files?

**Comment by cy-chengyan** [comment]
> Hi, can you upload recent log files?

I have solved this problem based on the suggestion of someone in the QQ group. 
steps:
1. stop the iotdb service.
2. remove all Compress-xx-xx files in directory '/data/datanode/system/compression_ratio'
3. touch a empty file named 'Compress-3000000000-1000000000'
4. restart the iotdb service.

**Comment by shuwenwei** [comment]
This PR https://github.com/apache/iotdb/pull/12875 may solve the problem in compaction module. However, a negative compression ratio is not expected. We need some logs to locate this problem

**Comment by cy-chengyan** [comment]
> This PR #12875 may solve the problem in compaction module. However, a negative compression ratio is not expected. We need some logs to locate this problem

Thx. Unfortunately, this bug caused the server's disk space usage to reach 100%, so I have deleted all the logs.
