### ISSUE TITLE
[Bug] 1.3.1升级到1.3.2后报错

### ISSUE THREAD

**Issue by TimXu0713** [apache/iotdb#12857]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.3.1

### Describe the bug and provide the minimal reproduce step

3c3d集群，从1.3.1升级1.3.2，confignode已经升级完成，升级第1个dn后，发现业务端执行SQL报错：

> 2024-07-04 13:40:44,441 [pool-47-IoTDB-DataNodeInternalRPC-Processor-7] WARN  o.a.i.d.p.t.i.DataNodeInternalRPCServiceImpl:319 - Deserialize FragmentInstance failed.
java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 2
        at org.apache.iotdb.db.queryengine.plan.planner.plan.node.process.FilterNode.deserialize(FilterNode.java:108)
        at org.apache.iotdb.db.queryengine.plan.planner.plan.node.PlanNodeType.deserialize(PlanNodeType.java:280)
        at org.apache.iotdb.db.queryengine.plan.planner.plan.node.PlanNodeType.deserialize(PlanNodeType.java:268)
        at org.apache.iotdb.db.queryengine.plan.planner.plan.PlanFragment.deserializeHelper(PlanFragment.java:189)
        at org.apache.iotdb.db.queryengine.plan.planner.plan.PlanFragment.deserializeHelper(PlanFragment.java:194)
        at org.apache.iotdb.db.queryengine.plan.planner.plan.PlanFragment.deserializeHelper(PlanFragment.java:194)
        at org.apache.iotdb.db.queryengine.plan.planner.plan.PlanFragment.deserializeHelper(PlanFragment.java:194)
        at org.apache.iotdb.db.queryengine.plan.planner.plan.PlanFragment.deserialize(PlanFragment.java:175)
        at org.apache.iotdb.db.queryengine.plan.planner.plan.FragmentInstance.deserializeFrom(FragmentInstance.java:211)
        at org.apache.iotdb.db.protocol.thrift.impl.DataNodeInternalRPCServiceImpl.sendFragmentInstance(DataNodeInternalRPCServiceImpl.java:317)
        at org.apache.iotdb.mpp.rpc.thrift.IDataNodeRPCService$Processor$sendFragmentInstance.getResult(IDataNodeRPCService.java:4905)
        at org.apache.iotdb.mpp.rpc.thrift.IDataNodeRPCService$Processor$sendFragmentInstance.getResult(IDataNodeRPCService.java:4885)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

，回退该节点到1.3.1后，部分时间序列合并时报错如下：

> 2024-07-04 14:40:38,531 [pool-28-IoTDB-Compaction-Worker-5] ERROR o.a.i.d.s.d.c.e.t.AbstractCompactionTask:481 - Failed to pass compaction validation, source seq files: [file is /data/datanode/data/sequence/root.S308/6/2834/1714449024832-31-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714507050150-33-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714651387776-34-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714700171832-35-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714701414783-36-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714701742080-37-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714717026124-38-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714724875233-39-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714724956240-40-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714726083831-41-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714726169406-42-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714726671809-43-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714731500940-44-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714733914187-45-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714733952170-46-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714734661215-47-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714734755451-48-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714735046614-49-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714735115071-50-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714735374645-51-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714735424034-52-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714735552020-53-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714735612504-54-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714737643561-55-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714737719982-56-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714737833503-57-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714741361167-58-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714759459182-59-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714789827716-60-0-0.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/6/2834/1714790972955-61-0-0.tsfile, status: COMPACTING], source unseq files: [], target files: [file is /data/datanode/data/sequence/root.S308/6/2834/1714449024832-31-1-0.tsfile, status: COMPACTING] 
2024-07-04 14:40:38,531 [pool-28-IoTDB-Compaction-Worker-5] ERROR o.a.i.d.s.d.c.e.t.AbstractCompactionTask:145 - INNER_SEQ-root.S308 [Compaction] Meet errors 6: Failed to pass compaction validation, sequence files has overlap, time partition id is 2834. 
2024-07-04 14:40:46,937 [pool-28-IoTDB-Compaction-Worker-2] ERROR o.a.i.d.s.d.u.TsFileResourceUtils:368 - Device root.S308.pr.SKB_01_6H_018.DXX0180 is overlapped between file is /data/datanode/data/sequence/root.S308/6/2834/1714100195594-18-0-1.tsfile, status: COMPACTING and file is /data/datanode/data/sequence/root.S308/6/2834/1714128330152-10-0-0.tsfile, status: NORMAL, end time in file is /data/datanode/data/sequence/root.S308/6/2834/1714100195594-18-0-1.tsfile, status: COMPACTING is 1714132800000, start time in file is /data/datanode/data/sequence/root.S308/6/2834/1714128330152-10-0-0.tsfile, status: NORMAL is 1714089600000 

### What did you expect to see?

正常升级

### What did you see instead?

升级失败，且回退也失败

### Anything else?

目前的情况，该如何处理

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by CritasWang** [comment]
建议
1. 不要直接回退版本（如担心升级风险，备份后再升级）
2. 每个节点都升级到新版本第一个问题应该就没了，集群间节点混合部署时可能会有部分消息格式不兼容

**Comment by TimXu0713** [comment]
请问如何备份，导出吗？

**Comment by CritasWang** [comment]
可以把 除了 data/datanode/data 之外的内容全部拷贝一份

**Comment by shuwenwei** [comment]
1.3.1 之前有用过更早的版本吗

**Comment by TimXu0713** [comment]
有的，1.2.1->1.2.2->1.3.0->1.3.1升级上来的。现在所有节点升级到1.3.2了，有两个DN节点报错误：

> 2024-07-04 15:42:52,307 [pool-32-IoTDB-Compaction-Worker-1] ERROR o.a.i.d.s.d.u.TsFileResourceUtils:371 - Device root.S308.pr.PFB_03_6H_023.DXX0520 is overlapped between file is /data/datanode/data/sequence/root.S308/3/2834/428631101831-29-0-0.tsfile, status: NORMAL and file is /data/datanode/data/sequence/root.S308/3/2834/1714128689938-11-0-2.tsfile, status: COMPACTING, end time in file is /data/datanode/data/sequence/root.S308/3/2834/428631101831-29-0-0.tsfile, status: NORMAL is 1714435200000, start time in file is /data/datanode/data/sequence/root.S308/3/2834/1714128689938-11-0-2.tsfile, status: COMPACTING is 1714132800000 
2024-07-04 15:42:52,307 [pool-32-IoTDB-Compaction-Worker-1] ERROR o.a.i.d.s.d.c.e.t.AbstractCompactionTask:501 - Failed to pass compaction validation, source seq files: [file is /data/datanode/data/sequence/root.S308/3/2834/857262203663-1-8-1.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/3/2834/1714128689938-11-0-1.tsfile, status: COMPACTING], source unseq files: [file is /data/datanode/data/unsequence/root.S308/3/2834/1714524363731-38-2-0.tsfile, status: COMPACTING, file is /data/datanode/data/unsequence/root.S308/3/2834/1714606371727-1749-1-0.tsfile, status: COMPACTING], target files: [file is /data/datanode/data/sequence/root.S308/3/2834/857262203663-1-8-2.tsfile, status: COMPACTING, file is /data/datanode/data/sequence/root.S308/3/2834/1714128689938-11-0-2.tsfile, status: COMPACTING] 
2024-07-04 15:42:52,307 [pool-32-IoTDB-Compaction-Worker-1] ERROR o.a.i.d.s.d.c.e.t.AbstractCompactionTask:157 - CROSS-root.S308 [Compaction] Meet errors 3: Failed to pass compaction validation, sequence files has overlap, time partition id is 2834. 
2024-07-04 15:42:52,549 [pool-6-thread-1071] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-1071-1502 
2024-07-04 15:42:54,238 [pool-6-thread-1069] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-1069-1500 
2024-07-04 15:42:56,192 [pool-6-thread-1070] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-1070-1501 
2024-07-04 15:42:57,546 [pool-6-thread-1073] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-1073-1506 
2024-07-04 15:42:59,238 [pool-6-thread-1066] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-1066-1497

**Comment by CritasWang** [comment]
某些数据文件里有意外的数据，可以停机后，在每个节点运行下这个
./tools/tsfile/check-overlap-sequence-files-and-repair.sh

**Comment by shuwenwei** [comment]
./tools/tsfile/check-overlap-sequence-files-and-repair.sh 的参数是顺序区目录

**Comment by TimXu0713** [comment]
好的。
另外一个问题，不知道算不算BUG，停止DN时报错，需要手动kill进程。

> [root@iotdb-wx-dn-03 opt]# ./apache-iotdb/sbin/stop-datanode.sh 
Check whether the rpc_port is used..., port is 6667 6667
lsof: unacceptable port specification in: -i :6667\n6667
lsof 4.87
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
[+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
No DataNode to stop
[root@iotdb-wx-dn-03 opt]# jps
41488 Jps
38473 DataNode
[root@iotdb-wx-dn-03 opt]# lsof -i:6667
COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
java    38473 root  311u  IPv6 12338683      0t0  TCP iotdb-wx-dn-03:ircu-3 (LISTEN)
java    38473 root  470u  IPv6 12293959      0t0  TCP iotdb-wx-dn-03:ircu-3->bogon:41052 (ESTABLISHED)
java    38473 root  472u  IPv6 12338094      0t0  TCP iotdb-wx-dn-03:ircu-3->bogon:6414 (ESTABLISHED)
java    38473 root  534u  IPv6 12337612      0t0  TCP iotdb-wx-dn-03:ircu-3->bogon:wago-io-system (ESTABLISHED)

**Comment by TimXu0713** [comment]
> ./tools/tsfile/check-overlap-sequence-files-and-repair.sh 的参数是顺序区目录

你好，按照你的方法，停机修复后，已经不报原来的时间序列重叠的错误了，但是还是每5秒钟报一次如下错误：

> [root@iotdb-wx-dn-01 apache-iotdb]# tail -f logs/log_datanode_all.log | grep ERROR
2024-07-04 16:10:27,294 [pool-6-thread-23] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-23-386 
2024-07-04 16:10:32,296 [pool-6-thread-22] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-22-385 
2024-07-04 16:10:37,298 [pool-6-thread-19] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-19-382 
2024-07-04 16:10:42,296 [pool-6-thread-16] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-16-377 
2024-07-04 16:10:47,294 [pool-6-thread-26] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-26-389 
2024-07-04 16:10:52,295 [pool-6-thread-17] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-17-378 
2024-07-04 16:10:57,295 [pool-6-thread-25] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-25-388 
2024-07-04 16:11:02,298 [pool-6-thread-20] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-20-383

**Comment by TimXu0713** [comment]
> > ./tools/tsfile/check-overlap-sequence-files-and-repair.sh 的参数是顺序区目录
> 
> 你好，按照你的方法，停机修复后，已经不报原来的时间序列重叠的错误了，但是还是每5秒钟报一次如下错误：
> 
> > [root@iotdb-wx-dn-01 apache-iotdb]# tail -f logs/log_datanode_all.log | grep ERROR
> > 2024-07-04 16:10:27,294 [pool-6-thread-23] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-23-386
> > 2024-07-04 16:10:32,296 [pool-6-thread-22] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-22-385
> > 2024-07-04 16:10:37,298 [pool-6-thread-19] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-19-382
> > 2024-07-04 16:10:42,296 [pool-6-thread-16] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-16-377
> > 2024-07-04 16:10:47,294 [pool-6-thread-26] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-26-389
> > 2024-07-04 16:10:52,295 [pool-6-thread-17] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-17-378
> > 2024-07-04 16:10:57,295 [pool-6-thread-25] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-25-388
> > 2024-07-04 16:11:02,298 [pool-6-thread-20] ERROR o.a.i.c.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-6-thread-20-383

不好意思，这个是业务数据导致的问题，不用管了，谢谢大佬，问题已经解决。

**Comment by CritasWang** [comment]
> 好的。 另外一个问题，不知道算不算BUG，停止DN时报错，需要手动kill进程。
> 
> > [root@iotdb-wx-dn-03 opt]# ./apache-iotdb/sbin/stop-datanode.sh
> > Check whether the rpc_port is used..., port is 6667 6667
> > lsof: unacceptable port specification in: -i :6667\n6667
> > lsof 4.87
> > latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
> > latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
> > latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
> > usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
> > [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
> > [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
> > Use the ``-h'' option to get more help information.
> > No DataNode to stop
> > [root@iotdb-wx-dn-03 opt]# jps
> > 41488 Jps
> > 38473 DataNode
> > [root@iotdb-wx-dn-03 opt]# lsof -i:6667
> > COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
> > java    38473 root  311u  IPv6 12338683      0t0  TCP iotdb-wx-dn-03:ircu-3 (LISTEN)
> > java    38473 root  470u  IPv6 12293959      0t0  TCP iotdb-wx-dn-03:ircu-3->bogon:41052 (ESTABLISHED)
> > java    38473 root  472u  IPv6 12338094      0t0  TCP iotdb-wx-dn-03:ircu-3->bogon:6414 (ESTABLISHED)
> > java    38473 root  534u  IPv6 12337612      0t0  TCP iotdb-wx-dn-03:ircu-3->bogon:wago-io-system (ESTABLISHED)

这个看看配置文件里面的端口是是不是配置了两遍(iotdb-datanode.properties 中的 dn_rpc_port)

**Comment by TimXu0713** [comment]
stop-datanode.sh中获取端口可以优化成如下这样，取最后一次的配置：

> dn_rpc_port=`sed '/^dn_rpc_port=/!d;s/.*=//' ${DATANODE_CONF}/iotdb-datanode.properties | awk 'END {print}'`
