### ISSUE TITLE
AttributeError: module 'iotdb.thrift.common.ttypes' has no attribute 'TShowConfigurationTemplateResp'

### ISSUE THREAD

**Issue by tianna1121** [apache/iotdb#12921]
I have already compiled, installed and started the iotdb server, I can access the iotdb server via restapi endpoint. The compiling command (master branch): 
`mvn clean package -pl distribution -am -DskipTests -Dthrift.download-url=http://apache.org/licenses/LICENSE-2.0.txt -Dthrift.exec.absolute.path=/opt/homebrew/bin/thrift`

However when I swich to apache-iotdb python client, I just get the following error message:

```
(.venv) (base) zy@yangs-MacBook-Pro getData % python main.py 
Traceback (most recent call last):
  File "/Users/zy/ws/trading/getData/main.py", line 2, in <module>
    from iotdb.Session import Session
  File "/Users/zy/ws/trading/getData/.venv/lib/python3.10/site-packages/iotdb/Session.py", line 26, in <module>
    from iotdb.utils.SessionDataSet import SessionDataSet
  File "/Users/zy/ws/trading/getData/.venv/lib/python3.10/site-packages/iotdb/utils/SessionDataSet.py", line 24, in <module>
    from iotdb.utils.IoTDBRpcDataSet import IoTDBRpcDataSet
  File "/Users/zy/ws/trading/getData/.venv/lib/python3.10/site-packages/iotdb/utils/IoTDBRpcDataSet.py", line 26, in <module>
    from iotdb.thrift.rpc.IClientRPCService import TSFetchResultsReq, TSCloseOperationReq
  File "/Users/zy/ws/trading/getData/.venv/lib/python3.10/site-packages/iotdb/thrift/rpc/IClientRPCService.py", line 10876, in <module>
    (0, TType.STRUCT, 'success', [iotdb.thrift.common.ttypes.TShowConfigurationTemplateResp, None], None, ),  # 0
AttributeError: module 'iotdb.thrift.common.ttypes' has no attribute 'TShowConfigurationTemplateResp'
```

The env: MacOS 14.5,  Thrift version 0.20.0, Python3.10.10.

**Comment by HTHou** [comment]
You can run `mvn clean package -pl iotdb-client/client-py -am -DskipTests` to get the python client.

**Comment by HTHou** [comment]
You can run `mvn clean package -pl iotdb-client/client-py -am -DskipTests` to get the python client.

**Comment by tianna1121** [comment]
> You can run `mvn clean package -pl iotdb-client/client-py -am -DskipTests` to get the python client.

Done.  However, the log shows the same error message when I restart iotdb server.
```
[INFO] Apache IoTDB Project Parent POM .................... SUCCESS [  2.652 s]
[INFO] IoTDB: Protocol .................................... SUCCESS [  0.155 s]
[INFO] IoTDB: Protocol: Thrift Commons .................... SUCCESS [  3.228 s]
[INFO] IoTDB: Client ...................................... SUCCESS [  0.079 s]
[INFO] IoTDB: Client: Python-API .......................... SUCCESS [  0.119 s]
[INFO] ------------------------------------------------------------------------
```

**Comment by HTHou** [comment]
A new version uploaded, please use the new one. 
https://pypi.org/project/apache-iotdb/1.3.2.post0/
