### ISSUE TITLE
当IoTDB重启的时候 连接异常

### ISSUE THREAD

**Issue by AlixZhao** [apache/iotdb#13265]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

Version
1.3.1

### Describe the bug and provide the minimal reproduce step

当我使用iotdb-session的Session范例的代码，连接上IoTDB之后，
使用IoTDB的stop-all.sh，start-all.sh的命令进行重启IoTDB，
那么，Session范例的代码，将永远无法连接上远程的IoTDB。

相关异常信息
Exception in thread "main" org.apache.iotdb.rpc.IoTDBConnectionException: Fail to reconnect to server. Please check server status.192.168.1.23:6667
at org.apache.iotdb.session.SessionConnection.(SessionConnection.java:132)
at org.apache.iotdb.session.Session.constructSessionConnection(Session.java:592)
at org.apache.iotdb.session.Session.open(Session.java:501)
at org.apache.iotdb.session.Session.open(Session.java:459)

### What did you expect to see?

当IoTDB重启后，使用iotdb-session的JAVA客户端应用，能够重新连接上IoTDB

### What did you see instead?

当IoTDB重启后，使用iotdb-session的JAVA客户端应用，就无法连接上IoTDB

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by CritasWang** [comment]
尝试按照描述的方式进行了尝试，未发现上述问题
