### ISSUE TITLE
同一个连接上多线程插入数据报错 (Concurrency error when multiply threads use the same JDBC connection.)

### ISSUE THREAD

**Issue by puroc** [apache/iotdb#1327]
我的测试代码如下：
`
package iotdb;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PerformanceTest2 {
    public static final String URL = "jdbc:iotdb://192.168.235.101:6667/";
    public static final int RECORD = 1000;
    public static final int DEVICE_NUM = 10;
    private static final int BATCH_NUM = 50;
    public static final int INTERVAL = 15;

    public static void createGroup() {
        try (Connection connection = DriverManager.getConnection(URL, "root", "root");
             Statement statement = connection.createStatement()) {
            try {
                statement.execute("SET STORAGE GROUP TO root.org1");
            } catch (Throwable e) {
                e.printStackTrace();
            }
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }

    public static void insert(String startTime) {

        List<Thread> list = new ArrayList<>();
        try (Connection connection = DriverManager.getConnection(URL, "root", "root");
             Statement statement = connection.createStatement()) {
            for (int i = 0; i < DEVICE_NUM; i++) {
                int finalI = i;
                Thread thread = new Thread(() -> {
                    try {
                        TimeUtils timeUtils = new TimeUtils();
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                        Date lastTime = sdf.parse(startTime);
                        for (int j = 0; j < RECORD; j++) {
                            String sql = "insert into root.org1.flow.device" + finalI + "(timestamp, forward_flow, reverse_flow, instant_flow) values(" + sdf.format(lastTime) + "," + 100 + "," + 0 + "," + 50 + ")";
                            statement.addBatch(sql);
                            lastTime = timeUtils.addSecond(lastTime, INTERVAL);
                            if (RECORD >= BATCH_NUM && j != 0 && j % BATCH_NUM == 0) {
                                statement.executeBatch();
                                statement.clearBatch();
                                System.out.println("batch insert");
                            }
                        }
                        statement.executeBatch();
                        statement.clearBatch();
                        System.out.println("final batch insert");
                    } catch (Throwable e) {
                        e.printStackTrace();
                    }
                });
                list.add(thread);
            }
            list.forEach(t -> {
                t.start();
            });

            list.forEach(t -> {
                try {
                    t.join();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            });
            System.out.println("insert finished.");
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) throws ClassNotFoundException, SQLException {
        Class.forName("org.apache.iotdb.jdbc.IoTDBDriver");
        createGroup();
        insert("2020-01-01 00:00:00");
        query();
    }

    private static void query() {
        try (Connection connection = DriverManager.getConnection(URL, "root", "root");
             Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery("select count(*) from root.org1");
            outputResult(resultSet);
        } catch (Throwable e) {
            e.printStackTrace();
        }
    }

    private static void outputResult(ResultSet resultSet) throws SQLException {
        if (resultSet != null) {
            System.out.println("--------------------------");
            final ResultSetMetaData metaData = resultSet.getMetaData();
            final int columnCount = metaData.getColumnCount();
            for (int i = 0; i < columnCount; i++) {
                System.out.print(metaData.getColumnLabel(i + 1) + " ");
            }
            System.out.println();
            while (resultSet.next()) {
                for (int i = 1; ; i++) {
                    System.out.print(resultSet.getString(i));
                    if (i < columnCount) {
                        System.out.print(", ");
                    } else {
                        System.out.println();
                        break;
                    }
                }
            }
            System.out.println("--------------------------\n");
        }
    }
}
`

报错信息如下：
`
java.sql.SQLException: Error occurs when closing statement.
	at org.apache.iotdb.jdbc.IoTDBStatement.closeClientOperation(IoTDBStatement.java:150)
	at org.apache.iotdb.jdbc.IoTDBStatement.close(IoTDBStatement.java:160)
	at iotdb.PerformanceTest2.insert(PerformanceTest2.java:94)
	at iotdb.PerformanceTest2.main(PerformanceTest2.java:102)
	Suppressed: java.sql.SQLException: Error occurs when closing session at server. Maybe server is down.
		at org.apache.iotdb.jdbc.IoTDBConnection.close(IoTDBConnection.java:120)
		... 2 more
	Caused by: org.apache.thrift.transport.TTransportException: Cannot write to null outputStream
		at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:140)
		at org.apache.thrift.protocol.TBinaryProtocol.writeI32(TBinaryProtocol.java:202)
		at org.apache.thrift.protocol.TBinaryProtocol.writeMessageBegin(TBinaryProtocol.java:117)
		at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:70)
		at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
		at org.apache.iotdb.service.rpc.thrift.TSIService$Client.send_closeSession(TSIService.java:182)
		at org.apache.iotdb.service.rpc.thrift.TSIService$Client.closeSession(TSIService.java:174)
		at org.apache.iotdb.jdbc.IoTDBConnection.close(IoTDBConnection.java:118)
		... 2 more
Caused by: org.apache.thrift.transport.TTransportException: Cannot write to null outputStream
	at org.apache.thrift.transport.TIOStreamTransport.write(TIOStreamTransport.java:140)
	at org.apache.thrift.protocol.TBinaryProtocol.writeI32(TBinaryProtocol.java:202)
	at org.apache.thrift.protocol.TBinaryProtocol.writeMessageBegin(TBinaryProtocol.java:117)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:70)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Client.send_closeOperation(TSIService.java:366)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Client.closeOperation(TSIService.java:358)
	at org.apache.iotdb.jdbc.IoTDBStatement.closeClientOperation(IoTDBStatement.java:145)
	... 3 more
`

**Comment by jixuan1989** [comment]
JDBC implementation is not thread-safe.
JDBC的实现不是线程安全的。
要做成连接池来测试。

**Comment by kqkdChen** [comment]
建议使用sessionPool插入数据，多线程可以共享
