### ISSUE TITLE
[Bug]  ERROR o.a.t.s.TThreadPoolServer$WorkerProcess:258 - Thrift Error occurred during processing of message.

### ISSUE THREAD

**Issue by richiewen8** [apache/iotdb#13293]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.3.2

### Describe the bug and provide the minimal reproduce step

SessionPool Connect Iotdb :
 sessionPool = new SessionPool(host, port, user, password, 1);
and  finally:
sessionPool.close();
 
close connect ,tail -f logs/log_datanode_all.log 

### What did you expect to see?

log info

### What did you see instead?

```bash
2024-08-25 19:44:37,621 [pool-28-IoTDB-ClientRPC-Processor-4] INFO  o.a.i.d.p.s.SessionManager:125 - IoTDB: Login status: Login successfully. User : root, opens Session-4-root:127.0.0.1:44896
2024-08-25 19:44:37,668 [pool-28-IoTDB-ClientRPC-Processor-4] INFO  o.a.i.d.p.t.i.ClientRPCServiceImpl:1210 - IoTDB server version: 1.3.2 (Build: aa0ff4a)
2024-08-25 19:46:12,751 [pool-28-IoTDB-ClientRPC-Processor-2] ERROR o.a.t.s.TThreadPoolServer$WorkerProcess:258 - Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:178)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
        at org.apache.iotdb.rpc.TElasticFramedTransport.readFrame(TElasticFramedTransport.java:122)
        at org.apache.iotdb.rpc.TElasticFramedTransport.read(TElasticFramedTransport.java:117)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:463)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:361)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:244)
        at org.apache.iotdb.db.protocol.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:50)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
        at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176)
        ... 12 common frames omitted
2024-08-25 19:46:12,751 [pool-28-IoTDB-ClientRPC-Processor-3] ERROR o.a.t.s.TThreadPoolServer$WorkerProcess:258 - Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:178)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
        at org.apache.iotdb.rpc.TElasticFramedTransport.readFrame(TElasticFramedTransport.java:122)
        at org.apache.iotdb.rpc.TElasticFramedTransport.read(TElasticFramedTransport.java:117)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:463)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:361)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:244)
        at org.apache.iotdb.db.protocol.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:50)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
        at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176)
        ... 12 common frames omitted
```

### Anything else?

nothing

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by CritasWang** [comment]
This log will not have any impact on the system.
In addition, the level of this log has been changed in subsequent Thrift versions, but it remains at the error level in IoTDB dependent versions

**Comment by Zy-X25** [comment]
windows2.0.5版报的还是error级别

**Comment by HTHou** [comment]
最新的master分支不打印这个日志了 https://github.com/apache/iotdb/pull/16797
