### ISSUE TITLE
[Bug] Apache IoTDB confignode - unable to start pod on OpenShift

### ISSUE THREAD

**Issue by 180Gio** [apache/iotdb#13484]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.3.2-confignode, 1.3.2-standalone, OS: Windows and OpenShift 4.16

### Describe the bug and provide the minimal reproduce step

ApacheIoTDB is unable to start in OpenShift due to error on creation of folder

```
----------------------------
Starting IoTDB ConfigNode
----------------------------
Notice: in some systems, ConfigNode must run in sudo mode to write data. The process may fail.
Checking whether the ports are already occupied...
Warning: If you do not use sudo, the checking may not detect all the occupied ports.
WARN:
WARN: the value of net.core.somaxconn (=4096) is too small, please set it to a larger value using the following command.
WARN:     sudo sysctl -w net.core.somaxconn=65535
WARN: The original net.core.somaxconn value will be set back when the os reboots.
WARN:
setting local JMX...
ConfigNode on heap memory size = 6552MB, off heap memory size = 1640MB
If you want to change this configuration, please check conf/confignode-env.sh.
2024-09-11 12:56:25,088 [main] INFO  o.a.i.c.c.ConfigNodeDescriptor:107 - Start to read config file file:/iotdb/sbin/../conf/iotdb-common.properties 
2024-09-11 12:56:25,094 [main] INFO  o.a.i.c.c.ConfigNodeDescriptor:129 - start reading ConfigNode conf file: file:/iotdb/sbin/../conf/iotdb-confignode.properties 
2024-09-11 12:56:25,166 [main] INFO  o.a.i.c.s.ConfigNode:106 - IoTDB-ConfigNode environment variables: 
	CONFIGNODE_HOME=/iotdb/sbin/..;
	CONFIGNODE_CONF=/iotdb/sbin/../conf; 
2024-09-11 12:56:25,167 [main] INFO  o.a.i.c.s.ConfigNode:110 - IoTDB-ConfigNode default charset is: UTF-8 
2024-09-11 12:56:25,169 [main] INFO  o.a.i.c.s.ConfigNodeCommandLine:68 - Running mode -s 
2024-09-11 12:56:25,170 [main] INFO  o.a.i.c.s.ConfigNodeCommandLine:72 - Starting IoTDB 1.3.1 (Build: 214695d) 
2024-09-11 12:56:25,173 [main] INFO  o.a.i.c.c.ConfigNodeStartupCheck:65 - configNode port check successful. 
2024-09-11 12:56:25,174 [main] INFO  o.a.i.c.s.StartupChecks:59 - Start JMX locally. 
2024-09-11 12:56:25,175 [main] INFO  o.a.i.c.s.StartupChecks:45 - JDK version is 11. 
2024-09-11 12:56:25,175 [main] INFO  o.a.i.c.c.ConfigNodeStartupCheck:201 - Make dirs: /iotdb/sbin/../data/confignode/system 
2024-09-11 12:56:25,176 [main] INFO  o.a.i.c.c.ConfigNodeStartupCheck:201 - Make dirs: /iotdb/sbin/../data/confignode/consensus 
2024-09-11 12:56:25,183 [main] INFO  o.a.i.c.s.ConfigNode:118 - Activating IoTDB-ConfigNode... 
2024-09-11 12:56:25,184 [main] INFO  o.a.i.c.s.RegisterManager:54 - The JMX ServerService service is started successfully, which takes 0 ms. 
2024-09-11 12:56:25,496 [main] INFO  o.a.i.c.s.ConfigNode:251 - Successfully setup internal services. 
2024-09-11 12:56:25,588 [main] INFO  o.a.i.c.a.a.BasicAuthorizer$InstanceHolder:104 - Authorizer provider class: org.apache.iotdb.commons.auth.authorizer.LocalFileAuthorizer 
2024-09-11 12:56:25,592 [main] INFO  o.a.i.c.a.u.LocalFileUserAccessor:399 - user info dir /iotdb/data/confignode/system/users is created 
2024-09-11 12:56:25,688 [main] INFO  o.a.i.c.a.u.BasicUserManager:129 - Admin initialized 
2024-09-11 12:56:25,690 [main] INFO  o.a.i.c.a.r.LocalFileRoleAccessor:270 - role info dir /iotdb/data/confignode/system/roles is created 
2024-09-11 12:56:25,723 [main] ERROR o.a.i.c.s.ConfigNode:299 - Can't start ConfigNode consensus group! 
java.io.IOException: Cannot create directory '/iotdb/sbin/../ext/udf/tmp'.
	at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2287)
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:1380)
	at org.apache.iotdb.commons.file.SystemFileFactory.makeDirIfNecessary(SystemFileFactory.java:82)
	at org.apache.iotdb.commons.udf.service.UDFExecutableManager.setupAndGetInstance(UDFExecutableManager.java:48)
	at org.apache.iotdb.confignode.persistence.UDFInfo.<init>(UDFInfo.java:78)
	at org.apache.iotdb.confignode.manager.ConfigManager.<init>(ConfigManager.java:261)
	at org.apache.iotdb.confignode.service.ConfigNode.initConfigManager(ConfigNode.java:297)
	at org.apache.iotdb.confignode.service.ConfigNode.active(ConfigNode.java:127)
	at org.apache.iotdb.confignode.service.ConfigNodeCommandLine.activeConfigNodeInstance(ConfigNodeCommandLine.java:97)
	at org.apache.iotdb.confignode.service.ConfigNodeCommandLine.run(ConfigNodeCommandLine.java:79)
	at org.apache.iotdb.commons.ServerCommandLine.doMain(ServerCommandLine.java:58)
	at org.apache.iotdb.confignode.service.ConfigNode.main(ConfigNode.java:114)
2024-09-11 12:56:25,724 [main] INFO  o.a.i.c.s.ConfigNode:409 - Deactivating IoTDB-ConfigNode... 
2024-09-11 12:56:25,724 [main] INFO  o.a.i.c.s.RegisterManager:73 - deregister all service. 
2024-09-11 12:56:25,724 [main] INFO  o.a.i.c.s.ConfigNode:415 - IoTDB-ConfigNode is deactivated. 
2024-09-11 12:56:25,759 [Thread-0] INFO  o.a.i.c.s.ConfigNodeShutdownHook:49 - ConfigNode exiting... 
Exception in thread "Thread-0" java.lang.NullPointerException
	at org.apache.iotdb.confignode.service.ConfigNodeShutdownHook.run(ConfigNodeShutdownHook.java:51)
```

### What did you expect to see?

Pod starting

### What did you see instead?

Pod crashing with error "CrashLoopBackOff"

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
@CritasWang do you have any clue about it?

**Comment by gzigurella** [comment]
Following the problem, facing the issue on OKD as well.

Tried on OKD (3 nodes on CentOS) and on a single-node K3S cluster on a Fedora 39, the latter is not experiencing the problem therefore I am guessing it could be a problem related to Network File System? Since it's the only notable difference I am facing between the two environments

**Comment by CritasWang** [comment]
What is the method of storage usage.
Perhaps we can consider mounting the directory for.
We did not encounter this situation in both k8s and k3s

**Comment by 180Gio** [comment]
I have a GPFS based on IBM Spectrum Scale, I don't know if I can handle it using mount because PVC and PV are handled by IBM Spectrum Scale. The drives are configured in RAID 3

**Comment by myysophia** [comment]
@SeanGaluzzi 
you can try this yaml without configmap。
- configNode
`
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iotdb-confignode
  namespace: iotdb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: iotdb-cn1.3
      app.kubernetes.io/name: iotdb-confignode
  serviceName: iotdb-confignode
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: iotdb-cn1.3
        app.kubernetes.io/name: iotdb-confignode
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - iotdb-confignode
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: MY_NS_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: cn_internal_address
          value: $(MY_POD_NAME).iotdb-confignode.$(MY_NS_NAME).svc.cluster.local
        - name: cn_seed_config_node
          value: iotdb-confignode-0.iotdb-confignode.$(MY_NS_NAME).svc.cluster.local:10710
        - name: schema_replication_factor
          value: "1"
        - name: data_replication_factor
          value: "1"
        - name: cn_internal_port
          value: "10710"
        - name: cn_consensus_port
          value: "10720"
        - name: schema_region_consensus_protocol_class
          value: org.apache.iotdb.consensus.ratis.RatisConsensus
        - name: config_node_consensus_protocol_class
          value: org.apache.iotdb.consensus.ratis.RatisConsensus
        - name: data_region_consensus_protocol_class
          value: org.apache.iotdb.consensus.iot.IoTConsensus
        - name: cn_metric_reporter_list
          value: PROMETHEUS
        - name: cn_metric_level
          value: CORE
        - name: cn_metric_prometheus_reporter_port
          value: "9092"
        image: apache/iotdb:1.3.2-confignode
        imagePullPolicy: IfNotPresent
        name: iotdb-confignode
        ports:
        - containerPort: 10710
          name: tcp-10710
          protocol: TCP
        - containerPort: 10720
          name: tcp-10720
          protocol: TCP
        - containerPort: 10730
          name: tcp-10730
          protocol: TCP
        - containerPort: 10740
          name: tcp-10740
          protocol: TCP
        - containerPort: 9092
          name: tcp-9092
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: host-time
        - mountPath: /iotdb/data/
          name: iotdb-confignode-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: iotdb-confignode-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: gp2
      volumeMode: Filesystem

`
- datanode
`
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iotdb-datanode
  namespace: iotdb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: iotdb-dn1.3
      app.kubernetes.io/name: iotdb-datanode
  serviceName: iotdb-datanode
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-08-14T11:07:05+08:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: iotdb-dn1.3
        app.kubernetes.io/name: iotdb-datanode
    spec:
      affinity:
        podAntiAffinity: {}
      containers:
      - env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_NS_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: dn_rpc_address
          value: $(MY_POD_NAME).iotdb-datanode.$(MY_NS_NAME).svc.cluster.local
        - name: dn_internal_address
          value: $(MY_POD_NAME).iotdb-datanode.$(MY_NS_NAME).svc.cluster.local
        - name: dn_seed_config_node
          value: iotdb-confignode-0.iotdb-confignode.$(MY_NS_NAME).svc.cluster.local:10710
        - name: schema_replication_factor
          value: "1"
        - name: data_replication_factor
          value: "1"
        - name: dn_rpc_port
          value: "6667"
        - name: dn_mpp_data_exchange_port
          value: "10740"
        - name: dn_schema_region_consensus_port
          value: "10750"
        - name: dn_data_region_consensus_port
          value: "10760"
        - name: schema_region_consensus_protocol_class
          value: org.apache.iotdb.consensus.ratis.RatisConsensus
        - name: config_node_consensus_protocol_class
          value: org.apache.iotdb.consensus.ratis.RatisConsensus
        - name: data_region_consensus_protocol_class
          value: org.apache.iotdb.consensus.iot.IoTConsensus
        - name: enable_auto_create_schema
          value: "true"
        - name: dn_metric_reporter_list
          value: PROMETHEUS
        - name: dn_metric_level
          value: CORE
        - name: dn_metric_prometheus_reporter_port
          value: "9091"
        image: apache/iotdb:1.3.2-datanode
        imagePullPolicy: IfNotPresent
        name: iotdb-datanode
        ports:
        - containerPort: 10710
          name: tcp-10710
          protocol: TCP
        - containerPort: 10720
          name: tcp-10720
          protocol: TCP
        - containerPort: 10730
          name: tcp-10730
          protocol: TCP
        - containerPort: 10740
          name: tcp-10740
          protocol: TCP
        - containerPort: 6667
          name: tcp-6667
          protocol: TCP
        - containerPort: 9091
          name: tcp-9091
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: host-time
        - mountPath: /iotdb/data/
          name: iotdb-datanode-data
        - mountPath: /iotdb/conf/datanode-env.sh
          name: iotdb-datanode-env
          subPath: datanode-env.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
      - configMap:
          defaultMode: 420
          items:
          - key: datanode-env.sh
            path: datanode-env.sh
          name: iotdb-datanode-env
        name: iotdb-datanode-env
      - configMap:
          defaultMode: 420
          items:
          - key: iotdb-common.properties
            path: ' /iotdb/conf/iotdb-common.properties'
          name: iotdb-common-env
        name: iotdb-common-env
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: iotdb-datanode-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: gp2
      volumeMode: Filesystem

`
