### ISSUE TITLE
iotdb 0.10.0 + grafana没有数据

### ISSUE THREAD

**Issue by pan2za** [apache/iotdb#2200]
**Describe the bug**
1 iotdb0.10.0
2 grafana from grafana.com latest windows version
3 iotdb-simplejson -grafana 0.11.0 from this github

**To Reproduce**

just connecting grafana to iotdb

**Expected behavior**
2020-12-06 11:24:52,836 [pool-5-IoTDB-RPC-Client-thread-2] ERROR org.apache.thrift.server.TThreadPoolServer$WorkerProcess:321 - Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125)
        ... 9 common frames omitted
2020-12-06 11:24:52,837 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:236 - IoTDB: receive close session
2020-12-06 11:25:13,327 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:176 - IoTDB: receive open session request from username root
2020-12-06 11:25:13,328 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:223 - IoTDB: Login status: Login successfully. User : root
2020-12-06 11:25:13,365 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:1059 - IoTDB server version: 0.10.1
2020-12-06 11:26:33,144 [pool-5-IoTDB-RPC-Client-thread-2] ERROR org.apache.thrift.server.TThreadPoolServer$WorkerProcess:321 - Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125)
        ... 9 common frames omitted
2020-12-06 11:26:33,145 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:236 - IoTDB: receive close session
2020-12-06 11:26:40,575 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:176 - IoTDB: receive open session request from username root
2020-12-06 11:26:40,575 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:223 - IoTDB: Login status: Login successfully. User : root
2020-12-06 11:26:40,611 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:1059 - IoTDB server version: 0.10.12020-12-06 11:24:52,836 [pool-5-IoTDB-RPC-Client-thread-2] ERROR org.apache.thrift.server.TThreadPoolServer$WorkerProcess:321 - Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125)
        ... 9 common frames omitted
2020-12-06 11:24:52,837 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:236 - IoTDB: receive close session
2020-12-06 11:25:13,327 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:176 - IoTDB: receive open session request from username root
2020-12-06 11:25:13,328 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:223 - IoTDB: Login status: Login successfully. User : root
2020-12-06 11:25:13,365 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:1059 - IoTDB server version: 0.10.1
2020-12-06 11:26:33,144 [pool-5-IoTDB-RPC-Client-thread-2] ERROR org.apache.thrift.server.TThreadPoolServer$WorkerProcess:321 - Thrift Error occurred during processing of message.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125)
        ... 9 common frames omitted
2020-12-06 11:26:33,145 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:236 - IoTDB: receive close session
2020-12-06 11:26:40,575 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:176 - IoTDB: receive open session request from username root
2020-12-06 11:26:40,575 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:223 - IoTDB: Login status: Login successfully. User : root
2020-12-06 11:26:40,611 [pool-5-IoTDB-RPC-Client-thread-2] INFO  org.apache.iotdb.db.service.TSServiceImpl:1059 - IoTDB server version: 0.10.1
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by HTHou** [comment]
Can you have a look? @Genius-pig

**Comment by qiaojialin** [comment]
Hi, this is due to the version mismatch. 
If you use IoTDB 0.10.0, please use the same big version of the iotdb-grafana-connector.

**Comment by pan2za** [comment]
嗯嗯，我改用0.11.0就好了。
