### ISSUE TITLE
 group by level & align by device NullPointer

### ISSUE THREAD

**Issue by qiaojialin** [apache/iotdb#2609]
0.11.2:

insert into root.turbine1.d1(timestamp,s1,s2) values(3,1,3);
select count(*) from root group by ([1,4), 3ms),level=2 align by device

Msg: 500: null

![image](https://user-images.githubusercontent.com/7240743/106422648-f0f08300-6499-11eb-878a-dd26c2ca1b97.png)

**Comment by HTHou** [comment]
I saw a different error message.
```
IoTDB> insert into root.turbine1.d1(timestamp,s1,s2) values(3,1,3);
insert into root.turbine1.d1(timestamp,s1,s2) values(3,1,3);
Msg: The statement is executed successfully.
IoTDB> select count(*) from root group by ([1,4), 3ms),level=2 align by device
select count(*) from root group by ([1,4), 3ms),level=2 align by device
Msg: 411: Error occurred in query process: * is not a legal path
```

Server:
```
11:27:13.141 [pool-8-IoTDB-RPC-Client-1] WARN DETAILED_FAILURE_QUERY_TRACE - Error occurred in query process: 
org.apache.iotdb.db.exception.query.QueryProcessException: org.apache.iotdb.db.exception.metadata.IllegalPathException: * is not a legal path
	at org.apache.iotdb.db.qp.strategy.PhysicalGenerator$AggPhysicalPlanRule.transform(PhysicalGenerator.java:490)
	at org.apache.iotdb.db.qp.strategy.PhysicalGenerator.transformQuery(PhysicalGenerator.java:525)
	at org.apache.iotdb.db.qp.strategy.PhysicalGenerator.doTransformation(PhysicalGenerator.java:259)
	at org.apache.iotdb.db.qp.strategy.PhysicalGenerator.transformToPhysicalPlan(PhysicalGenerator.java:146)
	at org.apache.iotdb.db.qp.Planner.parseSQLToPhysicalPlan(Planner.java:82)
	at org.apache.iotdb.db.service.TSServiceImpl.executeStatement(TSServiceImpl.java:650)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2433)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:1)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.iotdb.db.exception.metadata.IllegalPathException: * is not a legal path
	at org.apache.iotdb.db.metadata.MTree.getNodeByPath(MTree.java:580)
	at org.apache.iotdb.db.metadata.MTree.getSchema(MTree.java:500)
	at org.apache.iotdb.db.metadata.MManager.getSeriesType(MManager.java:700)
	at org.apache.iotdb.db.utils.SchemaUtils.getSeriesTypesByPaths(SchemaUtils.java:129)
	at org.apache.iotdb.db.qp.strategy.PhysicalGenerator.verifyAllAggregationDataTypesEqual(PhysicalGenerator.java:945)
	at org.apache.iotdb.db.qp.strategy.PhysicalGenerator.access$0(PhysicalGenerator.java:937)
	at org.apache.iotdb.db.qp.strategy.PhysicalGenerator$AggPhysicalPlanRule.transform(PhysicalGenerator.java:486)
	... 13 common frames omitted
11:27:13.150 [pool-8-IoTDB-RPC-Client-1] DEBUG IoTDB_AUDIT_LOGGER - IoTDB: receive close operation from Session 1
```

**Comment by Alima777** [comment]
Fixed. Throw an exception if group by is used with align by device.
