### ISSUE TITLE
20000个设备，每设备500传感器，16GB内存下使用iot-benchmark测试导致无法注册新序列 IoTDB system load is too large to create timeseries

### ISSUE THREAD

**Issue by jiayp** [apache/iotdb#2803]
**Describe the bug**
服务器16G内存,iotdb是初始50%内存，最大90%内存
20000个设备，每设备500传感器，10个client，5个存储组，使用iot-benchmark测试导致内存溢出。
0.11和master自己打的0.12.snapshot都一样。
按照 #2595 修改
tsfile_size_threshold=100000000
memtable_size_threshold=100M和10M都报错。

另外，这个memtable是每个存储组一个吗？
我希望能支持尽量多的设备，应该怎么做才合适？

**Comment by HTHou** [comment]
您好，根据您的描述，测试时是按照 #2595 所说关闭了`enable_mem_control`的选项是吗？只有关闭了这个选项memtable_size_threshold 的设置才会生效。

此外，修改memtable_size_threshold时必须要写成实际的数字，带M时暂时是不会正确识别，仍然为默认值256MB。另外，针对这个场景，还建议将primitive_array_size调整为32或者16。

根据您的描述场景，总共有20,000 * 500 = 1千万个传感器。当前的0.11和master版本的元数据存储模式可能对这个场景不太友好。目前我们正在进行这方面的优化工作，0.12正式版本发布后会对这种超多传感器的进行大幅优化，可以尽情期待一下。

**Comment by jiayp** [comment]
> 您好，根据您的描述，测试时是按照 #2595 所说关闭了`enable_mem_control`的选项是吗？只有关闭了这个选项memtable_size_threshold 的设置才会生效。
**测试过enable_mem_control位true时和false时，设置memtable_size_threshold时，上述变量改为false了。**
> 
> 此外，修改memtable_size_threshold时必须要写成实际的数字，带M时暂时是不会正确识别，仍然为默认值256MB。另外，针对这个场景，还建议将primitive_array_size调整为32或者16。
**10M时写的是10737418。**
> 
> 根据您的描述场景，总共有20,000 * 500 = 1千万个传感器。当前的0.11和master版本的元数据存储模式可能对这个场景不太友好。目前我们正在进行这方面的优化工作，0.12正式版本发布后会对这种超多传感器的场景进行大幅优化，可以尽情期待一下。
**master上现在和没合并这个改进吧？0.12预估什么时候能发布？**

**Comment by jiayp** [comment]
修改primitive_array_size为16后，还是报错

`2021-03-11 11:11:58,473 [pool-7-IoTDB-RPC-Client-thread-2] WARN  org.apache.iotdb.db.service.TSServiceImpl:1790 - meet error while processing non-query.
org.apache.iotdb.db.exception.query.QueryProcessException: org.apache.iotdb.db.exception.metadata.MetadataException: IoTDB system load is too large to create timeseries, please increase MAX_HEAP_SIZE in iotdb-env.sh/bat and restart
        at org.apache.iotdb.db.qp.executor.PlanExecutor.createTimeSeries(PlanExecutor.java:1067)
        at org.apache.iotdb.db.qp.executor.PlanExecutor.processNonQuery(PlanExecutor.java:225)
        at org.apache.iotdb.db.service.TSServiceImpl.executeNonQuery(TSServiceImpl.java:1152)
        at org.apache.iotdb.db.service.TSServiceImpl.executeNonQueryPlan(TSServiceImpl.java:1786)
        at org.apache.iotdb.db.service.TSServiceImpl.executeUpdateStatement(TSServiceImpl.java:1139)
        at org.apache.iotdb.db.service.TSServiceImpl.executeStatementInBatch(TSServiceImpl.java:462)
        at org.apache.iotdb.db.service.TSServiceImpl.executeBatchStatement(TSServiceImpl.java:434)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeBatchStatement.getResult(TSIService.java:2278)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeBatchStatement.getResult(TSIService.java:2258)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.iotdb.db.exception.metadata.MetadataException: IoTDB system load is too large to create timeseries, please increase MAX_HEAP_SIZE in iotdb-env.sh/bat and restart
        at org.apache.iotdb.db.metadata.MManager.createTimeseries(MManager.java:408)
        at org.apache.iotdb.db.metadata.MManager.createTimeseries(MManager.java:402)
        at org.apache.iotdb.db.qp.executor.PlanExecutor.createTimeSeries(PlanExecutor.java:1065)
        ... 14 common frames omitted
2021-03-11 11:11:58,473 [pool-7-IoTDB-RPC-Client-thread-2] WARN  org.apache.iotdb.db.service.TSServiceImpl:1790 - meet error while processing non-query.`

**Comment by HTHou** [comment]
> 修改primitive_array_size为16后，还是报错

哦，这个就是由于内存不足，传感器过多导致无法注册新序列导致的。跟 #2595的情况不太一样。

如果要在16G的机器上使用现在版本支持这个场景，建议将write_read_schema_free_memory_proportion里schema的比例调大一些，可以试试 3:2:3:2。

> master上现在和没合并这个改进吧？0.12预估什么时候能发布？

对，这个现在还正在开发中。大概3、4周左右应该就可以了。
