### ISSUE TITLE
golang client using  insertRecord function return status code exception

### ISSUE THREAD

**Issue by longlispace** [apache/iotdb#2934]
**Describe the bug**
golang client code path:  https://github.com/apache/iotdb-client-go/blob/main/example/session_example.go
An exception occurs when the code runs to the insertRecord function(Line 76)

**To Reproduce**
1. setup enviroments
export GO111MODULE=on
export GOPROXY=https://goproxy.io
mkdir session_example && cd session_example

2. download code
curl -o session_example.go -L https://github.com/apache/iotdb-client-go/raw/main/example/session_example.go
Comment out lines 77 through 110(Retaining 76 row insertRecord functions)

3. build and run
go mod init session_example
go mod tidy
go run session_example.go

golang client log:
2021/03/26 16:45:03 Error Code: 400

iotdb all log:
2021-03-26 17:08:47,603 [pool-7-IoTDB-RPC-Client-thread-8] ERROR org.apache.iotdb.db.service.TSServiceImpl:1417 - meet error when insert 
java.lang.ArrayIndexOutOfBoundsException: 1280
	at org.apache.iotdb.db.qp.physical.crud.InsertRowPlan.fillValues(InsertRowPlan.java:385)
	at org.apache.iotdb.db.qp.physical.crud.InsertRowPlan.<init>(InsertRowPlan.java:102)
	at org.apache.iotdb.db.service.TSServiceImpl.insertRecord(TSServiceImpl.java:1408)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$insertRecord.getResult(TSIService.java:2653)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$insertRecord.getResult(TSIService.java:2633)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2021-03-26 17:08:47,605 [pool-7-IoTDB-RPC-Client-thread-8] INFO  org.apache.iotdb.db.service.TSServiceImpl:277 - Session-38 is closing 
2021-03-26 17:09:33,327 [timedQuerySqlCountThread] INFO  org.apache.iotdb.db.service.TSServiceImpl:207 - Query count in current 1 minute: 1 

**Expected behavior**
Can use the insertrecord function to insert data

**Desktop (please complete the following information):**
 - OS: windows
 - Version: 0.11.2
[
[log_all.log](https://github.com/apache/iotdb/files/6218737/log_all.log)
](url)

**Comment by xiddjp** [comment]
I meet the same issue. Does anyone have a solution？

**Comment by jixuan1989** [comment]
we have noticed this and @manlge may fix it.
We also welcome more users joining us and provide your patch to fix it :D

**Comment by manlge** [comment]
Which version of iotdb server?
I test with https://repository.apache.org/content/repositories/snapshots/org/apache/iotdb/iotdb-distribution/0.12.0-SNAPSHOT/iotdb-distribution-0.12.0-20210408.004948-1-server-bin.zip
no problems was found.

**Comment by xiddjp** [comment]
0.11.2  @manlge

**Comment by xiddjp** [comment]
After I updated to v0.12.0, the problem did not recur. It seems to be OK. @manlge

**Comment by xiddjp** [comment]
After I updated to v0.12.0, the problem did not recur. It seems to be OK. @manlge

**Comment by xiddjp** [comment]
After I updated to v0.12.0, the problem did not recur. It seems to be OK. @manlge

**Comment by qiaojialin** [comment]
So the go client is for 0.12.0 :)
