### ISSUE TITLE
load configuration failed because Fail to reload configuration because java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by dyeaster** [apache/iotdb#3854]
**Describe the bug**
execute `load configuration` in Cli, exception  occured

**To Reproduce**
1. first start iotdb
2. use the Cli, execute 'load configuration'
3. exception description
> org.apache.iotdb.db.exception.query.QueryProcessException: Fail to reload config file file:sbin/../conf/iotdb-engine.properties because Fail to reload configuration because java.lang.NumberFormatException: null
        at org.apache.iotdb.db.conf.IoTDBDescriptor.loadHotModifiedProps(IoTDBDescriptor.java:1051)
        at org.apache.iotdb.db.qp.executor.PlanExecutor.loadConfiguration(PlanExecutor.java:1761)
        at org.apache.iotdb.db.qp.executor.PlanExecutor.processNonQuery(PlanExecutor.java:286)
        at org.apache.iotdb.db.service.TSServiceImpl.executeNonQuery(TSServiceImpl.java:1248)
        at org.apache.iotdb.db.service.TSServiceImpl.executeNonQueryPlan(TSServiceImpl.java:1910)
        at org.apache.iotdb.db.service.TSServiceImpl.executeUpdateStatement(TSServiceImpl.java:1236)
        at org.apache.iotdb.db.service.TSServiceImpl.executeStatement(TSServiceImpl.java:659)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2253)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2233)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

Some possible reasons :
after some tests, maybe the attribute below do not specify default values according to the source code.
max_deduplicated_path_num
frequency_interval_in_minute
slow_query_threshold
merge_write_throughput_mb_per_sec

**Comment by dyeaster** [comment]
> Try using the latest version? this problem was fixed in 3 July #3487
I use the latest version 0.12.1. After unzip the no configuration file has changed before iotdb server start. I just want to test the 'load configuration' in Cli.

**Comment by jixuan1989** [comment]
Hi, I feel confused.

> first start iotdb
> use the Cli, execute 'load configuration'
> exception description

It seems there is no any operation between starting the IoTDB and run 'load'.
But you also said 'after some tests, maybe the attribute below do not specify default values according to the source code.'

So, what is the correct reproduction steps?

**Comment by dyeaster** [comment]
> Hi, I feel confused.
> 
> > first start iotdb
> > use the Cli, execute 'load configuration'
> > exception description
> 
> It seems there is no any operation between starting the IoTDB and run 'load'.
> But you also said 'after some tests, maybe the attribute below do not specify default values according to the source code.'
> 
> So, what is the correct reproduction steps?

I am new to iotdb, so i want to know what happened when running 'load configuration';
according to the exception discription and stack trace, found the source code, IoTDBDescriptor.loadHotModifiedProps(Properties properties). 
![image](https://user-images.githubusercontent.com/33147167/131427909-cb5e72b8-84fa-4b71-8a7d-bf48d680fd28.png)
When uncomment the attribute line next (max_deduplicated_path_num,frequency_interval_in_minute,slow_query_threshold,merge_write_throughput_mb_per_sec) ,
![image](https://user-images.githubusercontent.com/33147167/131427995-a1483821-7ec9-438c-b2b8-980fe3d64fe6.png)
the command execute success.

when comment one of the attribute, this command execute failed and produce an exception.
![image](https://user-images.githubusercontent.com/33147167/131428071-7b27cb99-6c4f-48fd-951f-900998bfd221.png)

**Comment by HTHou** [comment]
> > Try using the latest version? this problem was fixed in 3 July #3487
> 
> I use the latest version 0.12.1. After unzip the no configuration file has changed before iotdb server start. I just want to test the 'load configuration' in Cli.

The mentioned PR is not in 0.12.1 but in 0.12.2, which will be released in few days.

**Comment by HTHou** [comment]
0.12.2 is released. Now you can upgrade to the new version.
