### ISSUE TITLE
这是什么错误 java.lang.UnsupportedOperationException: getFloat() is not supported for current sub-class

### ISSUE THREAD

**Issue by ohaTgxK9956562414460** [apache/iotdb#4771]
2022-01-11 15:57:36,511 [pool-6-IoTDB-Compaction-6] INFO  o.a.i.d.e.c.l.LevelCompactionTsFileManagement:805 - root.S0-0 [Compaction][Restore] target file /data/iotdb1/data/sequence/root.S0/0/0/1641124791961-858-1-0.tsfile is incomplete, delete it 
2022-01-11 15:57:36,511 [pool-6-IoTDB-Compaction-6] ERROR o.a.i.d.e.c.l.LevelCompactionTsFileManagement:696 - Error occurred in Compaction Merge thread 
java.lang.UnsupportedOperationException: getFloat() is not supported for current sub-class
        at org.apache.iotdb.tsfile.utils.TsPrimitiveType.getFloat(TsPrimitiveType.java:66)
        at org.apache.iotdb.db.utils.MergeUtils.writeTVPair(MergeUtils.java:71)
        at org.apache.iotdb.db.engine.compaction.utils.CompactionUtils.writeByDeserializePageMerge(CompactionUtils.java:211)
        at org.apache.iotdb.db.engine.compaction.utils.CompactionUtils.merge(CompactionUtils.java:410)
        at org.apache.iotdb.db.engine.compaction.level.LevelCompactionTsFileManagement.merge(LevelCompactionTsFileManagement.java:638)
        at org.apache.iotdb.db.engine.compaction.level.LevelCompactionTsFileManagement.merge(LevelCompactionTsFileManagement.java:526)
        at org.apache.iotdb.db.engine.compaction.TsFileManagement$CompactionMergeTask.call(TsFileManagement.java:181)
        at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.syncCompactOnePartition(StorageGroupProcessor.java:2002)
        at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.access$100(StorageGroupProcessor.java:135)
        at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor$CompactionAllPartitionTask.call(StorageGroupProcessor.java:524)
        at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.merge(StorageGroupProcessor.java:2138)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Desktop (please complete the following information):**
 - OS: centos7.5
 - Version apache-iotdb-0.12.4-all-bin

**Additional context**

**Comment by ohaTgxK9956562414460** [comment]
INFO  o.a.i.d.e.c.l.LevelCompactionTsFileManagement:805 - root.S0-0 [Compaction][Restore] target file /data/iotdb1/data/sequence/root.S0/0/0/1641124791961-858-1-0.tsfile is incomplete, delete it

**Comment by ohaTgxK9956562414460** [comment]
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/21187208/148906503-57e4fc2d-f5f7-4dcd-ac4c-69583017cc1d.png">

**Comment by THUMarkLau** [comment]
你好，麻烦加一下我的微信：MarkLauuu
