### ISSUE TITLE
Thrift Error occurred during processing of message

### ISSUE THREAD

**Issue by zhouzhiy** [apache/iotdb#4818]
**Describe the bug**
数据库能连接，无法查询，插入，执行语句一直卡着不动

org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.iotdb.rpc.TElasticFramedTransport.readFrame(TElasticFramedTransport.java:110)
	at org.apache.iotdb.rpc.TElasticFramedTransport.read(TElasticFramedTransport.java:105)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:455)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:354)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:243)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:125)
	... 12 common frames omitted

**Comment by jixuan1989** [comment]
we may need more info to diagnose the problem.
Could you provide a complete log_debug or log_info file?

**Comment by zhouzhiy** [comment]
[log_info.log](https://github.com/apache/iotdb/files/8031382/log_info.log)
[log-info-20220208.0.log.gz](https://github.com/apache/iotdb/files/8031388/log-info-20220208.0.log.gz)
大概在2022-2-9 14:20:00左右开始操作，操作顺序为：
1、执行插入
2、提示数据库进入readonly模式
3、当时可以查询
4、之后执行SET SYSTEM TO WRITABLE命令
5、再执行查询和插入操作，终端无响应

**Comment by HTHou** [comment]
> [log_info.log](https://github.com/apache/iotdb/files/8031382/log_info.log) [log-info-20220208.0.log.gz](https://github.com/apache/iotdb/files/8031388/log-info-20220208.0.log.gz) 大概在2022-2-9 14:20:00左右开始操作，操作顺序为： 1、执行插入 2、提示数据库进入readonly模式 3、当时可以查询 4、之后执行SET SYSTEM TO WRITABLE命令 5、再执行查询和插入操作，终端无响应

info日志里没看到什么具体的原因信息，可以发一下完整的log文件夹吗？
