### ISSUE TITLE
掉电后查询无法反序列化

### ISSUE THREAD

**Issue by 2594726366** [apache/iotdb#5107]
2022-02-22 15:34:59,357 [pool-15-IoTDB-RPC-Client-3] WARN  o.a.i.d.w.r.TsFileRecoverPerformer:170 - Cannot deserialize TsFileResource /home/iotdata/data/sequence/root.sg1/0/0/1644623407470-92743-1-0.tsfile, construct it using TsFileSequenceReader 
java.lang.IndexOutOfBoundsException: Invalid ordinal
	at org.apache.iotdb.db.engine.storagegroup.timeindex.TimeIndexLevel.valueOf(TimeIndexLevel.java:48)
	at org.apache.iotdb.db.engine.storagegroup.TsFileResource.deserialize(TsFileResource.java:257)
	at org.apache.iotdb.db.writelog.recover.TsFileRecoverPerformer.recoverResourceFromFile(TsFileRecoverPerformer.java:168)
	at org.apache.iotdb.db.writelog.recover.TsFileRecoverPerformer.recover(TsFileRecoverPerformer.java:104)
	at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.recoverTsFiles(StorageGroupProcessor.java:676)
	at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.recover(StorageGroupProcessor.java:446)
	at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.<init>(StorageGroupProcessor.java:393)
	at org.apache.iotdb.db.engine.StorageEngine.buildNewStorageGroupProcessor(StorageEngine.java:592)
	at org.apache.iotdb.db.engine.storagegroup.virtualSg.VirtualStorageGroupManager.getProcessor(VirtualStorageGroupManager.java:138)
	at org.apache.iotdb.db.engine.StorageEngine.getStorageGroupProcessorByPath(StorageEngine.java:568)
	at org.apache.iotdb.db.engine.StorageEngine.getProcessor(StorageEngine.java:511)
	at org.apache.iotdb.db.engine.StorageEngine.mergeLockAndInitQueryDataSource(StorageEngine.java:1066)
	at org.apache.iotdb.db.query.executor.RawDataQueryExecutor.initManagedSeriesReader(RawDataQueryExecutor.java:103)
	at org.apache.iotdb.db.query.executor.RawDataQueryExecutor.executeWithoutValueFilter(RawDataQueryExecutor.java:67)
	at org.apache.iotdb.db.query.executor.QueryRouter.rawDataQuery(QueryRouter.java:93)
	at org.apache.iotdb.db.qp.executor.PlanExecutor.processDataQuery(PlanExecutor.java:546)
	at org.apache.iotdb.db.qp.executor.PlanExecutor.processQuery(PlanExecutor.java:228)
	at org.apache.iotdb.db.service.TSServiceImpl.createQueryDataSet(TSServiceImpl.java:1110)
	at org.apache.iotdb.db.service.TSServiceImpl.internalExecuteQueryStatement(TSServiceImpl.java:738)
	at org.apache.iotdb.db.service.TSServiceImpl.executeStatement(TSServiceImpl.java:603)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2373)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2353)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2022-02-22 15:34:59,358 [pool-15-IoTDB-RPC-Client-3] WARN  o.a.i.d.s.TSServiceImpl:1976 - [INTERNAL_SERVER_ERROR] Exception occurred while executing " select * from root.sg1.d1".  
java.lang.IllegalArgumentException: Negative position
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:685)
	at org.apache.iotdb.tsfile.read.reader.LocalTsFileInput.read(LocalTsFileInput.java:90)
	at org.apache.iotdb.tsfile.read.TsFileSequenceReader.readTailMagic(TsFileSequenceReader.java:217)
	at org.apache.iotdb.tsfile.read.TsFileSequenceReader.loadMetadataSize(TsFileSequenceReader.java:190)
	at org.apache.iotdb.tsfile.read.TsFileSequenceReader.<init>(TsFileSequenceReader.java:128)
	at org.apache.iotdb.db.writelog.recover.TsFileRecoverPerformer.recoverResourceFromReader(TsFileRecoverPerformer.java:180)
	at org.apache.iotdb.db.writelog.recover.TsFileRecoverPerformer.recoverResourceFromFile(TsFileRecoverPerformer.java:174)
	at org.apache.iotdb.db.writelog.recover.TsFileRecoverPerformer.recover(TsFileRecoverPerformer.java:104)
	at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.recoverTsFiles(StorageGroupProcessor.java:676)
	at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.recover(StorageGroupProcessor.java:446)
	at org.apache.iotdb.db.engine.storagegroup.StorageGroupProcessor.<init>(StorageGroupProcessor.java:393)
	at org.apache.iotdb.db.engine.StorageEngine.buildNewStorageGroupProcessor(StorageEngine.java:592)
	at org.apache.iotdb.db.engine.storagegroup.virtualSg.VirtualStorageGroupManager.getProcessor(VirtualStorageGroupManager.java:138)
	at org.apache.iotdb.db.engine.StorageEngine.getStorageGroupProcessorByPath(StorageEngine.java:568)
	at org.apache.iotdb.db.engine.StorageEngine.getProcessor(StorageEngine.java:511)
	at org.apache.iotdb.db.engine.StorageEngine.mergeLockAndInitQueryDataSource(StorageEngine.java:1066)
	at org.apache.iotdb.db.query.executor.RawDataQueryExecutor.initManagedSeriesReader(RawDataQueryExecutor.java:103)
	at org.apache.iotdb.db.query.executor.RawDataQueryExecutor.executeWithoutValueFilter(RawDataQueryExecutor.java:67)
	at org.apache.iotdb.db.query.executor.QueryRouter.rawDataQuery(QueryRouter.java:93)
	at org.apache.iotdb.db.qp.executor.PlanExecutor.processDataQuery(PlanExecutor.java:546)
	at org.apache.iotdb.db.qp.executor.PlanExecutor.processQuery(PlanExecutor.java:228)
	at org.apache.iotdb.db.service.TSServiceImpl.createQueryDataSet(TSServiceImpl.java:1110)
	at org.apache.iotdb.db.service.TSServiceImpl.internalExecuteQueryStatement(TSServiceImpl.java:738)
	at org.apache.iotdb.db.service.TSServiceImpl.executeStatement(TSServiceImpl.java:603)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2373)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2353)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by HTHou** [comment]
这是那个版本的iotdb server?

**Comment by 2594726366** [comment]
apache-iotdb-0.12.4-server 这个版本

**Comment by 2594726366** [comment]
The size of this file is 0. Can I delete this file?
![image](https://user-images.githubusercontent.com/24288860/155259371-a7a482fc-8539-47bf-ab2b-9c87650e940c.png)

**Comment by 2594726366** [comment]
The size of this file is 0. Can I delete this file?
![image](https://user-images.githubusercontent.com/24288860/155259371-a7a482fc-8539-47bf-ab2b-9c87650e940c.png)

**Comment by HTHou** [comment]
> 

Yes, you can delete the tsfile and its resource and then restart the server.

**Comment by 2594726366** [comment]
Thank you. I started the service normally after deleting the file
