### ISSUE TITLE
0.12.5集群模式下

### ISSUE THREAD

**Issue by 391518331** [apache/iotdb#5817]
2022-05-06 19:19:24,825 [ClusterClient-7] ERROR o.a.t.s.TThreadPoolServer$WorkerProcess:258 - Thrift Error occurred during processing of message. 
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:178)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
        at org.apache.iotdb.rpc.TElasticFramedTransport.readFrame(TElasticFramedTransport.java:112)
        at org.apache.iotdb.rpc.TElasticFramedTransport.read(TElasticFramedTransport.java:107)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:463)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:361)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:244)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176)
        ... 12 common frames omitted

**Comment by 391518331** [comment]
Ensure that the 6567, 6667, 9003, 9004, 40010, 40011 and 31999 ports of the three nodes are open. If I want to monitor the service survival by TCP probe, which port should I monitor?

**Comment by OneSizeFitsQuorum** [comment]
You could use nodetools to [monitor](https://iotdb.apache.org/zh/UserGuide/Master/Maintenance-Tools/NodeTool.html) the server status. BTW, our cluster architecture is undergoing extensive reconstruction and is expected to be released in the summer. If business permits, you can wait a little bit~
