### ISSUE TITLE
java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by 391518331** [apache/iotdb#6122]
2022-06-01 14:30:24,638 [pool-13-IoTDB-RPC-Client-22] ERROR o.a.i.d.c.IoTDBDefaultThreadExceptionHandler:31 - Exception in thread pool-13-IoTDB-RPC-Client-22-75 
java.lang.NoSuchMethodError: org.apache.iotdb.db.qp.sql.IoTDBSqlParser$AttributeClausesContext.alias()Lorg/apache/iotdb/db/qp/sql/IoTDBSqlParser$AliasContext;
        at org.apache.iotdb.db.qp.sql.IoTDBSqlVisitor.parseAttributeClauses(IoTDBSqlVisitor.java:229)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlVisitor.visitCreateNonAlignedTimeseries(IoTDBSqlVisitor.java:202)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlVisitor.visitCreateNonAlignedTimeseries(IoTDBSqlVisitor.java:134)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlParser$CreateNonAlignedTimeseriesContext.accept(IoTDBSqlParser.java:1792)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlParserBaseVisitor.visitDdlStatement(IoTDBSqlParserBaseVisitor.java:34)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlParser$DdlStatementContext.accept(IoTDBSqlParser.java:550)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlParserBaseVisitor.visitStatement(IoTDBSqlParserBaseVisitor.java:27)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlParser$StatementContext.accept(IoTDBSqlParser.java:360)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlVisitor.visitSingleStatement(IoTDBSqlVisitor.java:164)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlVisitor.visitSingleStatement(IoTDBSqlVisitor.java:134)
        at org.apache.iotdb.db.qp.sql.IoTDBSqlParser$SingleStatementContext.accept(IoTDBSqlParser.java:289)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at org.apache.iotdb.db.qp.strategy.LogicalGenerator.generate(LogicalGenerator.java:102)
        at org.apache.iotdb.db.qp.Planner.parseSQLToPhysicalPlan(Planner.java:62)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.executeStatement(TSServiceImpl.java:613)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2853)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:2833)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by 391518331** [comment]
iotdb0.13 hadoop 3.3.2

**Comment by 391518331** [comment]
hadoop-tsfile-0.14.0-SNAPSHOT-jar-with-dependencies.jar
