### ISSUE TITLE
执行查询报错

### ISSUE THREAD

**Issue by huangdejie** [apache/iotdb#6363]
多线程进行查询，其中会出现错误，如下所示
![Uploading 1655798769100.png…]()
但是我单独将这条语句拿出来进行单元测试时未报错

**Comment by HTHou** [comment]
IoTDB 的版本和server端的具体报错日志？

**Comment by huangdejie** [comment]
> IoTDB 的版本和server端的具体报错日志？

版本为：iotdb-0.13.0
iotdb报错如下：
``2022-06-21 16:27:20,636 [pool-1975-IoTDB-Sub_RawQuery-2] ERROR o.a.i.d.q.d.RawQueryDataSetWithoutValueFilter$ReadTask:154 - Something gets wrong:  
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1645)
	at org.apache.iotdb.db.query.context.QueryContext.getPathModifications(QueryContext.java:94)
	at org.apache.iotdb.db.utils.FileLoaderUtils.loadTimeSeriesMetadata(FileLoaderUtils.java:125)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.loadTimeSeriesMetadata(SeriesReader.java:1125)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.unpackSeqTsFileResource(SeriesReader.java:1091)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.tryToUnpackAllOverlappedFilesToTimeSeriesMetadata(SeriesReader.java:1014)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.hasNextFile(SeriesReader.java:263)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.hasNextChunk(SeriesReader.java:336)
	at org.apache.iotdb.db.query.reader.series.SeriesRawDataBatchReader.readChunkData(SeriesRawDataBatchReader.java:170)
	at org.apache.iotdb.db.query.reader.series.SeriesRawDataBatchReader.hasNextBatch(SeriesRawDataBatchReader.java:118)
	at org.apache.iotdb.db.query.dataset.RawQueryDataSetWithoutValueFilter$ReadTask.runMayThrow(RawQueryDataSetWithoutValueFilter.java:96)
	at org.apache.iotdb.db.concurrent.WrappedRunnable.run(WrappedRunnable.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhaozhenzhou** [comment]
我也发现了这个问题，0.13.3版本，查询的时间序列为空时，就会报错
