### ISSUE TITLE
IoTDBDatabaseMetaData call getCatalogs Fail

### ISSUE THREAD

**Issue by huangdh12** [apache/iotdb#6640]
Exception in thread "main" java.lang.NullPointerException
 at org.apache.iotdb.jdbc.GroupedLSBWatermarkEncoder.<init>(GroupedLSBWatermarkEncoder.java:44)
 at org.apache.iotdb.jdbc.IoTDBDatabaseMetadata.getWatermarkEncoder(IoTDBDatabaseMetadata.java:295)
 at org.apache.iotdb.jdbc.IoTDBDatabaseMetadata.getCatalogs(IoTDBDatabaseMetadata.java:498)

![be17b5eed22df0d7550056628cdab82](https://user-images.githubusercontent.com/59213908/178395526-08cb58ef-8c7e-4b0b-8188-52adea6c232e.png)

![7c644ccb4c3115217b4d5eef08a84ef](https://user-images.githubusercontent.com/59213908/178395554-928af446-03cb-4280-9086-f73027cfd3ca.png)

**Comment by chinausers** [comment]
![1658212787770](https://user-images.githubusercontent.com/27771529/179682951-88ab3066-d7b2-419e-b493-3f496d67119e.png)
