### ISSUE TITLE
Completeness 函数调用出现错误

### ISSUE THREAD

**Issue by ccliushou** [apache/iotdb#6687]
查询语句：SELECT completeness(S202)  from root.XXX.XXXXXXXX  WHERE TIME >  2022-07-16T12:00:00

iotdb server错误信息如下：

2022-07-16 15:16:44,599 [pool-13-IoTDB-RPC-Client-2] WARN  o.a.i.d.u.ErrorHandlingUtils:61 - Status code: INTERNAL_SERVER_ERROR(500), operation: "SELECT completeness(S202)  from root.XXX.XXXXXXXX WHERE TIME >  2022-07-16T12:00:00". executeQueryStatement failed
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 14913, Size: 1
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.submitQueryTask(TSServiceImpl.java:785)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.executeQueryStatement(TSServiceImpl.java:658)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeQueryStatement.getResult(TSIService.java:2903)
        at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeQueryStatement.getResult(TSIService.java:2883)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.iotdb.db.service.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:64)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 14913, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.apache.iotdb.db.query.udf.datastructure.tv.ElasticSerializableTVList$LRUCache.get(ElasticSerializableTVList.java:365)
        at org.apache.iotdb.db.query.udf.datastructure.tv.ElasticSerializableTVList.getTime(ElasticSerializableTVList.java:117)
        at org.apache.iotdb.db.query.udf.core.layer.SingleInputColumnSingleReferenceIntermediateLayer$2.next(SingleInputColumnSingleReferenceIntermediateLayer.java:151)
        at org.apache.iotdb.db.query.udf.core.transformer.UDFQueryRowWindowTransformer.executeUDFOnce(UDFQueryRowWindowTransformer.java:40)
        at org.apache.iotdb.db.query.udf.core.transformer.UDFQueryTransformer.cacheValue(UDFQueryTransformer.java:54)
        at org.apache.iotdb.db.query.udf.core.transformer.Transformer.next(Transformer.java:49)
        at org.apache.iotdb.db.query.dataset.UDTFAlignByTimeDataSet.iterateReaderToNextValid(UDTFAlignByTimeDataSet.java:348)
        at org.apache.iotdb.db.query.dataset.UDTFAlignByTimeDataSet.fillBuffer(UDTFAlignByTimeDataSet.java:216)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.fillRpcReturnData(TSServiceImpl.java:1020)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.executeQueryPlan(TSServiceImpl.java:841)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.access$000(TSServiceImpl.java:163)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl$QueryTask.call(TSServiceImpl.java:221)
        at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl$QueryTask.call(TSServiceImpl.java:165)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 common frames omitted
2022-07-16 15:17:07,354 [pool-3-IoTDB-timedQuerySqlCount-1] INFO  o.a.i.d.s.b.QueryFrequencyRecorder:42 - Query count in current 1 minute 1

另外针对window参数的描述如下：
window：窗口大小，它是一个大于0的整数或者一个有单位的正数。前者代表每一个窗口包含的数据点数目，最后一个窗口的数据点数目可能会不足；后者代表窗口的时间跨度，目前支持五种单位，分别是'ms'（毫秒）、's'（秒）、'm'（分钟）、'h'（小时）和'd'（天）。缺省情况下，全部输入数据都属于同一个窗口。

“后者代表窗口的时间跨度”，不清晰具体是什么。示例中只有：
select completeness(s1,"window"="15") from root.test.d1 where time <= 2020-01-01 00:01:00

并没有时间跨度。

**Comment by ccliushou** [comment]
select completeness(s1,"window"="1h") from root.test.d1 where time <= 2020-01-01 00:01:00


这个写法，是看每1小时内，是否有数据吗？

**Comment by jixuan1989** [comment]
@543202718 @trin1t  could you give some help?

**Comment by trin1t** [comment]
> @543202718 @trin1t could you give some help?

This issue has been reported before. As far as I know, this issue may occur in an older version of IoTDB. You may try to update IoTDB to latest version.

**Comment by ccliushou** [comment]
> > @543202718 @trin1t could you give some help?
> 
> This issue has been reported before. As far as I know, this issue may occur in an older version of IoTDB. You may try to update IoTDB to latest version.

我当前用的版本是：

0.13.0

那就等0.14版本正式发布，我再试试。

**Comment by 543202718** [comment]
It is the same as issue #5520 and has been fixed it in PR #5568 .

**Comment by ccliushou** [comment]
3Q
