### ISSUE TITLE
IoTDB Cluster Error

### ISSUE THREAD

**Issue by tarungoswami** [apache/iotdb#6894]
Hello Team,

We are trying to run cluster using 2 servers say n1,n2(with 1C1D on each). With normal configuration the cluster is performing correctly.
Then to test data availability I stopped one of the datanode (say datanode of n2), after this when I ran some query to fetch the data,
it throws error like can't connect to datanode on n2. I tried to increase the replication factor as well, but when I changed the 
replication factor to 2 then I am having this issue.

    2022-08-04 02:43:40,679 [main] ERROR o.a.i.c.s.ConfigNodeCommandLine:71 - Meet error when doing start checking
    org.apache.iotdb.commons.exception.ConfigurationException: Parameter data_replication_factor can not be 2, please set to: 1
        at org.apache.iotdb.confignode.conf.ConfigNodeStartupCheck.checkGlobalConfig(ConfigNodeStartupCheck.java:103)
        at org.apache.iotdb.confignode.conf.ConfigNodeStartupCheck.startUpCheck(ConfigNodeStartupCheck.java:65)
        at org.apache.iotdb.confignode.service.ConfigNodeCommandLine.run(ConfigNodeCommandLine.java:69)
        at org.apache.iotdb.commons.ServerCommandLine.doMain(ServerCommandLine.java:58)
        at org.apache.iotdb.confignode.service.ConfigNode.main(ConfigNode.java:84)

**Comment by HTHou** [comment]
@WilliamSong112 PTAL

**Comment by wjr4hy** [comment]
因为默认的data_region_consensus_protocol_class 配置是standalone模式，所以副本只能设置为1，需改data_region_consensus_protocol_class 为其它模式，就可以设置多副本
