### ISSUE TITLE
0.13.0版本中enableRpcCompression  设置问题

### ISSUE THREAD

**Issue by ccliushou** [apache/iotdb#7200]
基于c#的原生方式访问iotdb，设置enableRpcCompression  为true后，服务端提示错误：

org.apache.thrift.protocol.TProtocolException: Bad version in readMessageBegin
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:248)
        at org.apache.iotdb.db.service.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:50)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

想用  start-cli.bat 测试是否有同样问题。。 但不知道在 start-cli.bat 如何设置  RpcCompression 呢？？

**Comment by HTHou** [comment]
1. 如果客户端设置enableRpcCompression = true, 服务端的配置有没有做相应的修改？
2. https://iotdb.apache.org/zh/UserGuide/V0.13.x/QuickStart/Command-Line-Interface.html#cli-%E8%BF%90%E8%A1%8C%E5%8F%82%E6%95%B0 可以加 -c

**Comment by lausannel** [comment]
已经解决了
https://github.com/eedalong/Apache-IoTDB-Client-CSharp/pull/81
