### ISSUE TITLE
load tsfile问题

### ISSUE THREAD

**Issue by honestpeople** [apache/iotdb#7487]
执行完 load tsfile命令之后，数据恢复到了unsequence下面，导致数据查询不到
版本13.2

**Comment by HTHou** [comment]
到unsequence下面是正常现象，数据查询不到的server端报错日志是？

**Comment by honestpeople** [comment]
> 到unsequence下面是正常现象，load的文件与已有的文件device时间范围有重叠。数据查询不到的server端报错日志是？

2022-09-30 09:50:49,672 [pool-14-IoTDB-RPC-Client-3] WARN  o.a.i.d.u.ErrorHandlingUtils:61 - Status code: INTERNAL_SERVER_ERROR(500), operation: "select p1 from root.bof.bof1". executeStatement failed 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.submitQueryTask(TSServiceImpl.java:802)
	at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.executeStatement(TSServiceImpl.java:631)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:3101)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:3081)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.iotdb.db.service.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:64)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException: null
	at org.apache.iotdb.tsfile.read.TsFileSequenceReader.<init>(TsFileSequenceReader.java:142)
	at org.apache.iotdb.tsfile.read.TsFileSequenceReader.<init>(TsFileSequenceReader.java:122)
	at org.apache.iotdb.db.query.control.FileReaderManager.get(FileReaderManager.java:129)
	at org.apache.iotdb.db.engine.cache.TimeSeriesMetadataCache.get(TimeSeriesMetadataCache.java:194)
	at org.apache.iotdb.db.utils.FileLoaderUtils.loadTimeSeriesMetadata(FileLoaderUtils.java:107)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.loadTimeSeriesMetadata(SeriesReader.java:1123)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.unpackSeqTsFileResource(SeriesReader.java:1089)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.tryToUnpackAllOverlappedFilesToTimeSeriesMetadata(SeriesReader.java:1012)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.hasNextFile(SeriesReader.java:260)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.hasNextChunk(SeriesReader.java:333)
	at org.apache.iotdb.db.query.reader.series.SeriesRawDataBatchReader.readChunkData(SeriesRawDataBatchReader.java:170)
	at org.apache.iotdb.db.query.reader.series.SeriesRawDataBatchReader.hasNextBatch(SeriesRawDataBatchReader.java:118)
	at org.apache.iotdb.db.query.dataset.RawQueryDataSetWithoutValueFilter$ReadTask.runMayThrow(RawQueryDataSetWithoutValueFilter.java:96)
	at org.apache.iotdb.db.concurrent.WrappedRunnable.run(WrappedRunnable.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 common frames omitted

**Comment by honestpeople** [comment]
> 到unsequence下面是正常现象，load的文件与已有的文件device时间范围有重叠。数据查询不到的server端报错日志是？

操作流程：flush->手动删除data下的data、system、wal->执行load “某个文件夹”->数据恢复到unsequence->查询数据报错

**Comment by HTHou** [comment]
手动删除data下的data、system、wal 是在iotdb启动的时候执行的？

**Comment by honestpeople** [comment]
> 手动删除data下的data、system、wal 是在iotdb启动的时候执行的？

在iotdb 运行中执行的

**Comment by HTHou** [comment]
运行中执行手动删除data目录是非常危险的，会导致很多未知问题。将手动删除data下的data、system、wal 这一步改成先停止iotdb 后再执行试试吧。
