### ISSUE TITLE
0.14版本程序执行报错IoTDBConnectionException: Fail to reconnect to server，但是数据能正常写入

### ISSUE THREAD

**Issue by jjli777** [apache/iotdb#7748]
数据库部署在云上，ip地址设置的服务器的ipv4地址，本地使用服务器的公网ip连接，执行插入序列不会报错，但是插入数据会报错，日志报错显示服务器的ipv4地址
org.apache.iotdb.rpc.IoTDBConnectionException: org.apache.iotdb.rpc.IoTDBConnectionException: Fail to reconnect to server. Please check server status.172.18.203.227:6668
	at org.apache.iotdb.session.Session.handleRedirection(Session.java:878)
	at org.apache.iotdb.session.Session.insertTablet(Session.java:2134)
	at org.apache.iotdb.session.pool.SessionPool.insertTablet(SessionPool.java:574)
	at org.apache.iotdb.session.pool.SessionPool.insertTablet(SessionPool.java:549)

**Comment by HTHou** [comment]
Need to set EnableRedirection to false in sessionPool.
