### ISSUE TITLE
为什么1.0版本的iotdb无法启动

### ISSUE THREAD

**Issue by zerolbsony** [apache/iotdb#8446]
2022-12-14 11:01:05,155 [main] ERROR o.a.i.db.service.DataNode:273 - Cannot register datanode with wrong id. Maybe it's already remo
ved, or it has another datanode's run-time properties. 
2022-12-14 11:01:05,156 [main] ERROR o.a.i.db.service.DataNode:181 - Fail to start server 
org.apache.iotdb.commons.exception.StartupException: Cannot register to the cluster.
        at org.apache.iotdb.db.service.DataNode.registerInConfigNode(DataNode.java:274)
        at org.apache.iotdb.db.service.DataNode.doAddNode(DataNode.java:160)
        at org.apache.iotdb.db.service.DataNodeServerCommandLine.run(DataNodeServerCommandLine.java:95)
        at org.apache.iotdb.commons.ServerCommandLine.doMain(ServerCommandLine.java:58)
        at org.apache.iotdb.db.service.DataNode.main(DataNode.java:132)
2022-12-14 11:01:05,165 [main] ERROR o.a.i.db.service.DataNode:676 - Stop data node error 
java.lang.NullPointerException: null
        at org.apache.iotdb.db.service.DataNode.stop(DataNode.java:673)
        at org.apache.iotdb.db.service.DataNode.doAddNode(DataNode.java:182)
        at org.apache.iotdb.db.service.DataNodeServerCommandLine.run(DataNodeServerCommandLine.java:95)
        at org.apache.iotdb.commons.ServerCommandLine.doMain(ServerCommandLine.java:58)
        at org.apache.iotdb.db.service.DataNode.main(DataNode.java:132)
2022-12-14 11:06:20,768 [main] ERROR o.a.i.db.service.DataNode:273 - Cannot register datanode with wrong id. Maybe it's already remo
ved, or it has another datanode's run-time properties. 
2022-12-14 11:06:20,770 [main] ERROR o.a.i.db.service.DataNode:181 - Fail to start server 
org.apache.iotdb.commons.exception.StartupException: Cannot register to the cluster.
        at org.apache.iotdb.db.service.DataNode.registerInConfigNode(DataNode.java:274)
        at org.apache.iotdb.db.service.DataNode.doAddNode(DataNode.java:160)
        at org.apache.iotdb.db.service.DataNodeServerCommandLine.run(DataNodeServerCommandLine.java:95)
        at org.apache.iotdb.commons.ServerCommandLine.doMain(ServerCommandLine.java:58)
        at org.apache.iotdb.db.service.DataNode.main(DataNode.java:132)
2022-12-14 11:06:20,778 [main] ERROR o.a.i.db.service.DataNode:676 - Stop data node error 
java.lang.NullPointerException: null
        at org.apache.iotdb.db.service.DataNode.stop(DataNode.java:673)
        at org.apache.iotdb.db.service.DataNode.doAddNode(DataNode.java:182)
        at org.apache.iotdb.db.service.DataNodeServerCommandLine.run(DataNodeServerCommandLine.java:95)
        at org.apache.iotdb.commons.ServerCommandLine.doMain(ServerCommandLine.java:58)
        at org.apache.iotdb.db.service.DataNode.main(DataNode.java:132)

**Comment by zerolbsony** [comment]
是dn_开头的配置对应的目录非空所致，清空后正常。
