### ISSUE TITLE
[Bug] v1.0.0 Java Session.open() exception

### ISSUE THREAD

**Issue by automatous** [apache/iotdb#8462]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

        <dependency>
            <groupId>org.apache.iotdb</groupId>
            <artifactId>iotdb-session</artifactId>
            <version>1.0.0</version>
        </dependency>

### Describe the bug and provide the minimal reproduce step

        <dependency>
            <groupId>org.apache.iotdb</groupId>
            <artifactId>iotdb-session</artifactId>
            <version>1.0.0</version>
        </dependency>

new Session.Builder()
                .version(Version.enum)
                .build()
the Version.enum only has Version.V_0_12, Version.V_0_13
default is SessionConfig.DEFAULT_VERSION = Version.V_0_13

### What did you expect to see?

Make 1.0.0 Session.open() successfully and Session‘s function is work well

### What did you see instead?

org.apache.iotdb.rpc.IoTDBConnectionException: Fail to reconnect to server. Please check server status.127.0.0.1:6667

	at org.apache.iotdb.session.SessionConnection.<init>(SessionConnection.java:102)
	at org.apache.iotdb.session.Session.constructSessionConnection(Session.java:428)
	at org.apache.iotdb.session.Session.open(Session.java:394)
	at org.apache.iotdb.session.Session.open(Session.java:377)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by qiaojialin** [comment]
Hi, please give information about the IoTDB(version, configuration).

**Comment by automatous** [comment]
docker:
apache/iotdb:1.0.0-1c1d
docker run -d -p 6667:6667 --name iotdb-1c1d apache/iotdb:1.0.0-1c1d

    <dependency>
        <groupId>org.apache.iotdb</groupId>
        <artifactId>iotdb-session</artifactId>
        <version>1.0.0</version>
    </dependency>

SessionConfig.DEFAULT_VERSION = Version.V_0_13
(PS: The version information has not been updated)
