### ISSUE TITLE
[Bug]  iotdb 1.0  regionReplicaSet is invalid: null

### ISSUE THREAD

**Issue by zhengshubin** [apache/iotdb#8735]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

centos 7.4 iotdb 1.0

### Describe the bug and provide the minimal reproduce step

SQL:

SELECT   

	last_value(green_warning_lamp) as green_warning_lamp,
	last_value(blue_warning_lamp) as blue_warning_lamp,
	last_value(red_warning_lamp) as red_warning_lamp,
	last_value(yellow_warning_lamp) as yellow_warning_lamp
FROM root.aa.bb.**
WHERE Time> 2023-01-04 12:00:00
align by device
当时间过滤条件设置为较新时 如 now-1h，会报 
java.lang.IllegalArgumentException: regionReplicaSet is invalid: null
        at org.apache.iotdb.db.mpp.plan.planner.distribution.SimpleFragmentParallelPlanner.selectTargetDataNode(SimpleFragmentParallelPlanner.java:129)
        at org.apache.iotdb.db.mpp.plan.planner.distribution.SimpleFragmentParallelPlanner.produceFragmentInstance(SimpleFragmentParallelPlanner.java:115)
        at org.apache.iotdb.db.mpp.plan.planner.distribution.SimpleFragmentParallelPlanner.prepare(SimpleFragmentParallelPlanner.java:87)
        at org.apache.iotdb.db.mpp.plan.planner.distribution.SimpleFragmentParallelPlanner.parallelPlan(SimpleFragmentParallelPlanner.java:78)
        at org.apache.iotdb.db.mpp.plan.planner.distribution.DistributionPlanner.planFragmentInstances(DistributionPlanner.java:94)
        at org.apache.iotdb.db.mpp.plan.planner.distribution.DistributionPlanner.planFragments(DistributionPlanner.java:78)
        at org.apache.iotdb.db.mpp.plan.execution.QueryExecution.doDistributedPlan(QueryExecution.java:304)
        at org.apache.iotdb.db.mpp.plan.execution.QueryExecution.start(QueryExecution.java:201)
        at org.apache.iotdb.db.mpp.plan.Coordinator.execute(Coordinator.java:150)
        at org.apache.iotdb.db.service.thrift.impl.ClientRPCServiceImpl.executeStatementInternal(ClientRPCServiceImpl.java:215)
        at org.apache.iotdb.db.service.thrift.impl.ClientRPCServiceImpl.executeStatementV2(ClientRPCServiceImpl.java:390)
        at org.apache.iotdb.service.rpc.thrift.IClientRPCService$Processor$executeStatementV2.getResult(IClientRPCService.java:3453)
        at org.apache.iotdb.service.rpc.thrift.IClientRPCService$Processor$executeStatementV2.getResult(IClientRPCService.java:3433)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.iotdb.db.service.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:64)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
regionReplicaSet is invalid: null

### What did you expect to see?

success query

### What did you see instead?

regionReplicaSet is invalid: null

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JackieTien97** [comment]
可以在cli里explain一下这个sql，然后把结果贴到issue里
```
EXPLAIN
SELECT
last_value(green_warning_lamp) as green_warning_lamp,
last_value(blue_warning_lamp) as blue_warning_lamp,
last_value(red_warning_lamp) as red_warning_lamp,
last_value(yellow_warning_lamp) as yellow_warning_lamp
FROM root.aa.bb.**
WHERE Time> 2023-01-04 12:00:00
align by device
```

**Comment by JackieTien97** [comment]
这个bug大概率在最新的rel/1.0分支已经fix了，你可以拉取最新的rel/1.0分支自己编译一个版本，也可以等这个月中旬v1.0.1正式发布

**Comment by zhengshubin** [comment]
> 可以在cli里explain一下这个sql，然后把结果贴到issue里
> 
> ```
> EXPLAIN
> SELECT
> last_value(green_warning_lamp) as green_warning_lamp,
> last_value(blue_warning_lamp) as blue_warning_lamp,
> last_value(red_warning_lamp) as red_warning_lamp,
> last_value(yellow_warning_lamp) as yellow_warning_lamp
> FROM root.aa.bb.**
> WHERE Time> 2023-01-04 12:00:00
> align by device
> ```

EXPLAIN 不出来
+-----------------+
|distribution plan|
+-----------------+
+-----------------+
Empty set.
