### ISSUE TITLE
[Bug] Cannot invoke "java.util.Map.get(Object)" because "headerMap" is null

### ISSUE THREAD

**Issue by li-tianpeng** [apache/iotdb#9572]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

version 1.1.0 (Build: 807ec8b-dev)

### Describe the bug and provide the minimal reproduce step

REST API V2
REQUEST:   select bf63, 5a3b, 2bb0, b890, dece, 21bf from root.read where time >= 2023-04-10 07:56:42 and time <= 2023-04-10 11:16:42 order by time asc
RESPONSE: code=305,message=Cannot invoke "java.util.Map.get(Object)" because "headerMap" is null

2023-04-10 11:16:42,572 [qtp462487268-62] WARN  o.a.i.d.p.r.v.h.ExceptionHandler:84 - Cannot invoke "java.util.Map.get(Object)" because "headerMap" is null
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "headerMap" is null
        at org.apache.iotdb.db.protocol.rest.v2.handler.QueryDataSetHandler.fillQueryDataSetWithTimestamps(QueryDataSetHandler.java:181)
        at org.apache.iotdb.db.protocol.rest.v2.handler.QueryDataSetHandler.fillDataSetWithTimestamps(QueryDataSetHandler.java:78)
        at org.apache.iotdb.db.protocol.rest.v2.handler.QueryDataSetHandler.fillQueryDataSet(QueryDataSetHandler.java:60)
        at org.apache.iotdb.db.protocol.rest.v2.impl.RestApiServiceImpl.executeQueryStatement(RestApiServiceImpl.java:166)
        at org.apache.iotdb.db.protocol.rest.v2.RestApi.executeQueryStatement(RestApi.java:85)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
        at org.apache.iotdb.db.protocol.rest.filter.ApiOriginFilter.doFilter(ApiOriginFilter.java:37)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:833)

### What did you expect to see?

There is no issue about "java.util.Map.get(Object)" because "headerMap" is null

### What did you see instead?

none

### Anything else?

none

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HTHou** [comment]
@CloudWise-Lukemiao  PTAL

**Comment by SteveYurongSu** [comment]
Please make sure that the version of grafana plugin and the version of iotdb is the same. @li-tianpeng

**Comment by li-tianpeng** [comment]
您好，我在官网上下载的版本，应该是一致的吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/iotdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月10日(星期一) 下午3:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/iotdb] [Bug] Cannot invoke "java.util.Map.get(Object)" because "headerMap" is null (Issue #9572)





 
Please make sure that the version of grafana plugin and the version of iotdb is the same. @li-tianpeng

**Comment by li-tianpeng** [comment]
> > 您好，我在官网上下载的版本，应该是一致的吧。
> > […](#)
> 
> Can you provide several examples of data storage or insertion? select bf63, 5a3b, 2bb0, b890, dece, 21bf from root.read where time >= 2023-04-10 07:56:42 and time <= 2023-04-10 11:16:42 order by time asc
some data like this, timeseries names are exactly the same.
IoTDB> select last * from root.*
+-----------------------------+-----------------------------------------------+------------------+--------+
|                         Time|                                     Timeseries|             Value|DataType|
+-----------------------------+-----------------------------------------------+------------------+--------+
|2023-04-11T09:42:01.534+08:00| root.read.5a3bef0cp9eedp4652p8537p38dc216fc49b|              77.0|  DOUBLE|
|2023-04-11T09:39:55.022+08:00| root.read.dece0cc8pdaa2p4d21pa401pd09bc9b162fc|               0.0|  DOUBLE|
|2023-04-11T09:41:25.229+08:00| root.read.b8902691p3916p45aepb412p6f883e92878e|     5877.28655298|  DOUBLE|
|2023-04-11T09:41:37.639+08:00| root.read.2bb0513bp9465p45e2pad10pba20f5cc5034|     7.54159268452|  DOUBLE|
|2023-04-11T09:41:01.221+08:00| root.read.21bfeffdp4016p43d9p9932p89bbe2970dc7|               0.0|   FLOAT|
|2023-04-11T09:42:02.073+08:00| root.read.bf63c0ecp9baap41e1p97ecpa96e0d038c7c|               0.0|  DOUBLE|
+-----------------------------+-----------------------------------------------+------------------+--------+
Total line number = 15
It costs 0.012s

**Comment by CloudWise-Lukemiao** [comment]
> 7.54159268452
I did not find any issues when using rest/v2/query to provide data examples. It is possible that the IoTDB version I am using or the format of the inserted data may be different from yours. Can you provide a download link and the method of inserting data?
<img width="886" alt="image" src="https://user-images.githubusercontent.com/76942485/231048994-c208b80d-2e83-47e8-8320-10ffbdbe2fe6.png">

**Comment by CloudWise-Lukemiao** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/76942485/231081456-f0c0b702-d378-438d-ad43-32b7188d1ed3.png">
Execute a show version to verify if the information is consistent

**Comment by li-tianpeng** [comment]
> <img alt="image" width="516" src="https://user-images.githubusercontent.com/76942485/231081456-f0c0b702-d378-438d-ad43-32b7188d1ed3.png">
> 
> Execute a show version to verify if the information is consistent

<img width="565" alt="image" src="https://user-images.githubusercontent.com/129806116/231092747-366d55e7-836a-4bbd-a2ec-68fc98dff13e.png">

**Comment by li-tianpeng** [comment]
> <img alt="image" width="837" src="https://user-images.githubusercontent.com/76942485/231109458-7063143d-680e-421f-a3ed-2b4ea36a2136.png">
> 
> <img alt="image" width="727" src="https://user-images.githubusercontent.com/76942485/231109516-3a0b396f-7aab-41a0-a31c-07763cb00ecd.png">
> 
> I used the provided data and the self generated data, but unfortunately this issue has not been reproduced. Do you have any other operations?



> > <img alt="image" width="516" src="https://user-images.githubusercontent.com/76942485/231081456-f0c0b702-d378-438d-ad43-32b7188d1ed3.png">
> > Execute a show version to verify if the information is consistent
> 
> <img alt="image" width="565" src="https://user-images.githubusercontent.com/129806116/231092747-366d55e7-836a-4bbd-a2ec-68fc98dff13e.png">

There was no other special operations，I inserted data according to https://iotdb.apache.org/zh/UserGuide/V1.1.x/Write-Data/REST-API.html#rest-api%E5%86%99%E5%85%A5.
Is there something wrong when datanode is not ready?
btw, iotdb works well today.

**Comment by m4xweber** [comment]
@li-tianpeng have you resolved this issue? I'm running into the same problem.

**Comment by li-tianpeng** [comment]
Not yet,&nbsp;Occasional.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/iotdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 晚上11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/iotdb] [Bug] Cannot invoke "java.util.Map.get(Object)" because "headerMap" is null (Issue #9572)





 
@li-tianpeng have you resolved this issue? I'm running into the same problem.

**Comment by CloudWise-Lukemiao** [comment]
> @li-tianpeng have you resolved this issue? I'm running into the same problem.

I am following up on this issue, but unfortunately I have not reproduced it yet. Can you provide a reproduction process

**Comment by li-tianpeng** [comment]
> > @li-tianpeng have you resolved this issue? I'm running into the same problem.
> 
> I am following up on this issue, but unfortunately I have not reproduced it yet. Can you provide a reproduction process

Thank you @Lukemiao. I think I insert data when iotdb start at the begining,  ping is OK, but memery has not initialization completed

**Comment by CloudWise-Lukemiao** [comment]
> > > @li-tianpeng have you resolved this issue? I'm running into the same problem.
> > 
> > 
> > I am following up on this issue, but unfortunately I have not reproduced it yet. Can you provide a reproduction process
> 
> Thank you @lukemiao. I think I insert data when iotdb start at the begining, ping is OK, but memery has not initialization completed

Can you provide me with a contact information? My email is 282583553@qq.com You can send the contact to my email

**Comment by li-tianpeng** [comment]
> > > > @li-tianpeng have you resolved this issue? I'm running into the same problem.
> > > 
> > > 
> > > I am following up on this issue, but unfortunately I have not reproduced it yet. Can you provide a reproduction process
> > 
> > 
> > Thank you @lukemiao. I think I insert data when iotdb start at the begining, ping is OK, but memery has not initialization completed
> 
> Can you provide me with a contact information? My email is [282583553@qq.com](mailto:282583553@qq.com) You can send the contact to my email

My email is 50332071@qq.com
