### ISSUE TITLE
[Bug] throw BufferUnderflowException when use M4

### ISSUE THREAD

**Issue by xianzheTM** [apache/iotdb#9920]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

docker image: apache/iotdb:1.1.0-standalone
and java library:
```
implementation 'org.apache.iotdb:iotdb-session:1.1.0'
```

### Describe the bug and provide the minimal reproduce step

**query by this in cli:**
```
select M4(`10017`,'timeInterval'='163947','displayWindowBegin'='1684731424764','displayWindowEnd'='1684817824764') as value from root.fcs.`-8888888`"
```
It's successfully.

But use the same sql in java library,It's failed.

And this's data:

```
IoTDB> select `10017` from root.fcs.`-8888888`
+------------------------+---------------------------+
|                    Time|root.fcs.`-8888888`.`10017`|
+------------------------+---------------------------+
|2023-04-22T05:05:12.342Z|                        0.0|
|2023-04-22T05:05:33.422Z|                        0.0|
|2023-04-22T05:05:44.221Z|                        0.0|
|2023-04-22T05:06:05.361Z|                        0.0|
|2023-04-22T05:06:16.182Z|                        0.0|
|2023-04-22T05:06:37.301Z|                        0.0|
|2023-04-22T05:06:48.142Z|                        0.0|
```

### What did you expect to see?

should query scuuessfully by java library

### What did you see instead?

```
2023-05-23 04:57:05,740 [Query-Worker-Thread-0$20230523_045704_00135_1.1.0.1] ERROR o.a.i.d.m.e.o.p.TransformOperator:182 - TransformOperator#hasNext() 
java.nio.BufferUnderflowException: null
        at java.base/java.nio.Buffer.nextGetIndex(Unknown Source)
        at java.base/java.nio.HeapByteBuffer.getLong(Unknown Source)
        at org.apache.iotdb.tsfile.utils.ReadWriteIOUtils.readLong(ReadWriteIOUtils.java:568)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.SerializableDoubleTVList.deserialize(SerializableDoubleTVList.java:66)
        at org.apache.iotdb.db.mpp.transformation.datastructure.SerializableList.deserialize(SerializableList.java:162)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.ElasticSerializableTVList$LRUCache.get(ElasticSerializableTVList.java:379)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.ElasticSerializableTVList.getTime(ElasticSerializableTVList.java:116)
        at org.apache.iotdb.db.mpp.transformation.dag.intermediate.SingleInputColumnSingleReferenceIntermediateLayer$3.yield(SingleInputColumnSingleReferenceIntermediateLayer.java:319)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.multi.UDFQueryRowWindowTransformer.tryExecuteUDFOnce(UDFQueryRowWindowTransformer.java:41)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.multi.UniversalUDFQueryTransformer.yieldValue(UniversalUDFQueryTransformer.java:44)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.Transformer.yield(Transformer.java:64)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.iterateReaderToNextValid(TransformOperator.java:161)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.iterateAllColumnsToNextValid(TransformOperator.java:146)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.hasNext(TransformOperator.java:178)
        at org.apache.iotdb.db.mpp.execution.operator.Operator.hasNextWithTimer(Operator.java:61)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.processInternal(Driver.java:220)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.lambda$processFor$1(Driver.java:144)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.tryWithLock(Driver.java:308)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.processFor(Driver.java:125)
        at org.apache.iotdb.db.mpp.execution.schedule.DriverTaskThread.execute(DriverTaskThread.java:69)
        at org.apache.iotdb.db.mpp.execution.schedule.AbstractDriverThread.run(AbstractDriverThread.java:73)
2023-05-23 04:57:05,744 [pool-36-IoTDB-ClientRPC-Processor-3] WARN  o.a.i.d.u.ErrorHandlingUtils:89 - Status code: 301, Query Statement: "select M4(`10017`,'timeInterval'='163947','displayWindowBegin'='1684731424764','displayWindowEnd'='1684817824764') as value from root.fcs.`-8888888`". executeStatement failed 
org.apache.iotdb.commons.exception.IoTDBException: java.lang.RuntimeException: java.nio.BufferUnderflowException
        at org.apache.iotdb.db.mpp.plan.execution.QueryExecution.dealWithException(QueryExecution.java:479)
        at org.apache.iotdb.db.mpp.plan.execution.QueryExecution.getResult(QueryExecution.java:462)
        at org.apache.iotdb.db.mpp.plan.execution.QueryExecution.getByteBufferBatchResult(QueryExecution.java:497)
        at org.apache.iotdb.db.utils.QueryDataSetUtils.convertQueryResultByFetchSize(QueryDataSetUtils.java:254)
        at org.apache.iotdb.db.service.thrift.impl.ClientRPCServiceImpl.lambda$static$0(ClientRPCServiceImpl.java:166)
        at org.apache.iotdb.db.service.thrift.impl.ClientRPCServiceImpl.executeStatementInternal(ClientRPCServiceImpl.java:239)
        at org.apache.iotdb.db.service.thrift.impl.ClientRPCServiceImpl.executeStatementV2(ClientRPCServiceImpl.java:480)
        at org.apache.iotdb.db.service.thrift.impl.ClientRPCServiceImpl.executeQueryStatementV2(ClientRPCServiceImpl.java:470)
        at org.apache.iotdb.service.rpc.thrift.IClientRPCService$Processor$executeQueryStatementV2.getResult(IClientRPCService.java:3579)
        at org.apache.iotdb.service.rpc.thrift.IClientRPCService$Processor$executeQueryStatementV2.getResult(IClientRPCService.java:3559)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.iotdb.db.service.thrift.ProcessorWithMetrics.process(ProcessorWithMetrics.java:64)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.nio.BufferUnderflowException
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.hasNext(TransformOperator.java:183)
        at org.apache.iotdb.db.mpp.execution.operator.Operator.hasNextWithTimer(Operator.java:61)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.processInternal(Driver.java:220)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.lambda$processFor$1(Driver.java:144)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.tryWithLock(Driver.java:308)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.processFor(Driver.java:125)
        at org.apache.iotdb.db.mpp.execution.schedule.DriverTaskThread.execute(DriverTaskThread.java:69)
        at org.apache.iotdb.db.mpp.execution.schedule.AbstractDriverThread.run(AbstractDriverThread.java:73)
Caused by: java.nio.BufferUnderflowException: null
        at java.base/java.nio.Buffer.nextGetIndex(Unknown Source)
        at java.base/java.nio.HeapByteBuffer.getLong(Unknown Source)
        at org.apache.iotdb.tsfile.utils.ReadWriteIOUtils.readLong(ReadWriteIOUtils.java:568)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.SerializableDoubleTVList.deserialize(SerializableDoubleTVList.java:66)
        at org.apache.iotdb.db.mpp.transformation.datastructure.SerializableList.deserialize(SerializableList.java:162)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.ElasticSerializableTVList$LRUCache.get(ElasticSerializableTVList.java:379)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.ElasticSerializableTVList.getTime(ElasticSerializableTVList.java:116)
        at org.apache.iotdb.db.mpp.transformation.dag.intermediate.SingleInputColumnSingleReferenceIntermediateLayer$3.yield(SingleInputColumnSingleReferenceIntermediateLayer.java:319)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.multi.UDFQueryRowWindowTransformer.tryExecuteUDFOnce(UDFQueryRowWindowTransformer.java:41)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.multi.UniversalUDFQueryTransformer.yieldValue(UniversalUDFQueryTransformer.java:44)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.Transformer.yield(Transformer.java:64)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.iterateReaderToNextValid(TransformOperator.java:161)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.iterateAllColumnsToNextValid(TransformOperator.java:146)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.hasNext(TransformOperator.java:178)
        ... 7 common frames omitted
2023-05-23 04:57:05,745 [Query-Worker-Thread-0$20230523_045704_00135_1.1.0.1] WARN  o.a.i.d.m.e.s.AbstractDriverThread:79 - [ExecuteFailed] 
java.lang.RuntimeException: java.lang.RuntimeException: java.nio.BufferUnderflowException
        at org.apache.iotdb.db.mpp.execution.driver.Driver.processInternal(Driver.java:231)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.lambda$processFor$1(Driver.java:144)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.tryWithLock(Driver.java:308)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.processFor(Driver.java:125)
        at org.apache.iotdb.db.mpp.execution.schedule.DriverTaskThread.execute(DriverTaskThread.java:69)
        at org.apache.iotdb.db.mpp.execution.schedule.AbstractDriverThread.run(AbstractDriverThread.java:73)
Caused by: java.lang.RuntimeException: java.nio.BufferUnderflowException
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.hasNext(TransformOperator.java:183)
        at org.apache.iotdb.db.mpp.execution.operator.Operator.hasNextWithTimer(Operator.java:61)
        at org.apache.iotdb.db.mpp.execution.driver.Driver.processInternal(Driver.java:220)
        ... 5 common frames omitted
Caused by: java.nio.BufferUnderflowException: null
        at java.base/java.nio.Buffer.nextGetIndex(Unknown Source)
        at java.base/java.nio.HeapByteBuffer.getLong(Unknown Source)
        at org.apache.iotdb.tsfile.utils.ReadWriteIOUtils.readLong(ReadWriteIOUtils.java:568)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.SerializableDoubleTVList.deserialize(SerializableDoubleTVList.java:66)
        at org.apache.iotdb.db.mpp.transformation.datastructure.SerializableList.deserialize(SerializableList.java:162)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.ElasticSerializableTVList$LRUCache.get(ElasticSerializableTVList.java:379)
        at org.apache.iotdb.db.mpp.transformation.datastructure.tv.ElasticSerializableTVList.getTime(ElasticSerializableTVList.java:116)
        at org.apache.iotdb.db.mpp.transformation.dag.intermediate.SingleInputColumnSingleReferenceIntermediateLayer$3.yield(SingleInputColumnSingleReferenceIntermediateLayer.java:319)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.multi.UDFQueryRowWindowTransformer.tryExecuteUDFOnce(UDFQueryRowWindowTransformer.java:41)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.multi.UniversalUDFQueryTransformer.yieldValue(UniversalUDFQueryTransformer.java:44)
        at org.apache.iotdb.db.mpp.transformation.dag.transformer.Transformer.yield(Transformer.java:64)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.iterateReaderToNextValid(TransformOperator.java:161)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.iterateAllColumnsToNextValid(TransformOperator.java:146)
        at org.apache.iotdb.db.mpp.execution.operator.process.TransformOperator.hasNext(TransformOperator.java:178)
        ... 7 common frames omitted
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wanghui42** [comment]
we fixed it, you can downloadhttps://github.com/thulab/iotdb-daily-build/releases/tag/2023-06-07-java8-apache-iotdb
