### ISSUE TITLE
[Bug] NPE Exception in log_datanode_error.log

### ISSUE THREAD

**Issue by LangYuanzh** [apache/iotdb#9963]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.1.0

### Describe the bug and provide the minimal reproduce step

2023-05-29 04:02:28,465 [pool-16-IoTDB-Compaction-9] ERROR o.a.i.d.e.c.e.t.CrossSpaceCompactionTask:251 - root.test-7 [Compaction] Meet errors in cross space compaction.
java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.iotdb.db.engine.compaction.execute.performer.impl.FastCompactionPerformer.perform(FastCompactionPerformer.java:154)
        at org.apache.iotdb.db.engine.compaction.execute.task.CrossSpaceCompactionTask.doCompaction(CrossSpaceCompactionTask.java:160)
        at org.apache.iotdb.db.engine.compaction.execute.task.AbstractCompactionTask.start(AbstractCompactionTask.java:80)
        at org.apache.iotdb.db.engine.compaction.schedule.CompactionWorker.run(CompactionWorker.java:65)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null

### What did you expect to see?

no error

### What did you see instead?

error log

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by choubenson** [comment]
We need more complete logs to diagnose, thanks.

**Comment by choubenson** [comment]
This is my WeChat id: benson19971204. Welcome to contact me.

**Comment by choubenson** [comment]
Thank you very much for submitting questions about iotdb, we welcome any questions and potential issues from users. In order to further analyze the problem, we need some data files, please add my WeChat (benson19971204), we can solve the problem faster :)

**Comment by choubenson** [comment]
It will be triggered when there is an empty chunk or empty page in the aligned timeseries, and it has been fixed in https://github.com/apache/iotdb/pull/9720.
